feat: 🎸 render engine and zoom api
SAP/cloud-sdk-ios-fiori pull request #185
Opened 2020-12-09 23:22 UTC by shengxu7

2020-12-10 00:05 UTC, MarcoEidinger commented
@shengxu7 please apply code formatting to project. Thanks

2020-12-10 17:55 UTC, MarcoEidinger reviewed
See my comments. I leave approval decision to @billzhou0223

2020-12-10 17:55 UTC, MarcoEidinger commented on Sources/FioriCharts/Charts/BubbleChart/BubbleIndicatorView.swift
> +    // swiftlint:disable force_unwrapping
Disabling swiftlint rules should be last resort and then for particular code places only. This statement will disable the rule until the end of the file (or until the linter sees a matching enable comment). 

Can `??` be used to provide an alternative to avoid force unwrapping? In SwiftUI the use of `.map` is also useful to avoid force unwrapping

2020-12-10 17:55 UTC, MarcoEidinger commented on Sources/FioriCharts/Charts/Common/GridLinesAndChartView.swift
> +    // swiftlint:disable cyclomatic_complexity
Disabling swiftlint rules should be last resort and then for particular code places only. This statement will disable the rule until the end of the file (or until the linter sees a matching enable comment). 

In addition to the Cyclomatic Complexity I see a high Cognitive Complexity (in general for FioriCharts code). Do you believe this could be simplified by refactoring into smaller, more precise functions?

As you are the main maintainer in the team I leave it up to you and @billzhou0223 if this shall be changed or not

2020-12-10 17:55 UTC, MarcoEidinger commented on Sources/FioriCharts/Charts/Common/XYAxisChart.swift
> +    // swiftlint:disable cyclomatic_complexity
Disabling swiftlint rules should be last resort and then for particular code places only. This statement will disable the rule until the end of the file (or until the linter sees a matching enable comment). 

In addition to the Cyclomatic Complexity I see a high Cognitive Complexity (in general for FioriCharts code). Do you believe this could be simplified by refactoring into smaller, more precise functions?

As you are the main maintainer in the team I leave it up to you and @billzhou0223 if this shall be changed or not

2020-12-10 17:55 UTC, MarcoEidinger commented on Sources/FioriCharts/Charts/LineChart/LineIndicatorView.swift
> +    // swiftlint:disable cyclomatic_complexity
Disabling swiftlint rules should be last resort and then for particular code places only. This statement will disable the rule until the end of the file (or until the linter sees a matching enable comment). 

In addition to the Cyclomatic Complexity I see a high Cognitive Complexity (in general for FioriCharts code). Do you believe this could be simplified by refactoring into smaller, more precise functions?

As you are the main maintainer in the team I leave it up to you and @billzhou0223 if this shall be changed or not

2020-12-10 18:03 UTC, shengxu7 commented on Sources/FioriCharts/Charts/BubbleChart/BubbleIndicatorView.swift
> +    // swiftlint:disable force_unwrapping
that code is outdated.

2020-12-10 19:44 UTC, billzhou0223 commented on Sources/FioriCharts/Charts/Common/XYAxisChart.swift
> +    // swiftlint:disable cyclomatic_complexity
Agreed. It's best practice to only disable the rules for the section desired. You can try this

```
// swiftlint:disable [function_body_length cyclomatic_complexity]
func functionName {}
// swiftlint:enable [function_body_length cyclomatic_complexity]
```   

2020-12-10 19:44 UTC, billzhou0223 commented on Sources/FioriCharts/Charts/LineChart/LineIndicatorView.swift
> +    // swiftlint:disable cyclomatic_complexity
Same as above

2020-12-10 19:50 UTC, billzhou0223 requested changes
See coments above.

2020-12-11 00:15 UTC, billzhou0223 approved these changes

2020-12-11 00:36 UTC, merged