feat: 🎸 Data Table for new Design
SAP/cloud-sdk-ios-fiori pull request #209
Opened 2021-03-03 00:54 UTC by ShawnMa16

implement new design for data table

2021-04-21 20:42 UTC, billzhou0223 requested changes
Please fix those missing doc warnings later.

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableDataView.swift
> +public struct TableDataView: View {
How about rename to `DataTable`?

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TestData.swift
> +import Foundation
Theses should be test app code. So I will move it into example project.

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +    @Published var firstRowSticky: Bool = false
According to Apple naming convension, we should call it `isFirstRowSticky`

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +    @Published var horizontalScrolling: Bool = true
I would expect it to be `isScrollEnable` which controls both directions instead of just horizontal scrolling.

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +public class TableModel: ObservableObject, Identifiable, NSCopying {
Where is the flag for pinch and zoom gesture? I remember we agreed that we will deliver the initial version of pinch-and-zoom in this release and enhance it in the future. It should be set to false (disabled) by default.

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +public class TableModel: ObservableObject, Identifiable, NSCopying {
I am thinking to have Model only contains data related properties(headerData, rowData). All other properties (isFirstRowSticky, isScrollEnable, columnAttributes, etc) should be stored in DataTable instead. 

We can keep this for now and discuss later.

2021-04-21 20:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +    public init(headerData: TableRowItem? = nil,
Did you miss `columnAttributes` in the params list of init?

2021-04-22 03:16 UTC, ShawnMa16 commented on Sources/FioriSwiftUICore/DataTable/DataItem.swift
> +    public enum Image {
The objectItemView only has the `DetailImage` property, that's why I didn't add those

2021-04-22 03:20 UTC, ShawnMa16 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +    @Published var horizontalScrolling: Bool = true
This is the idea from the designer.
The vertical scrolling will always be available while the developer can disable the horizontal scrolling

2021-04-22 03:20 UTC, ShawnMa16 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +public class TableModel: ObservableObject, Identifiable, NSCopying {
I will add that

2021-04-23 19:21 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableLayoutManager.swift
> +            if let _ = row.trailingAccessory {
This one needs to be fixed. We should follow the recommended coding style.

2021-04-23 19:22 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableViewLayout.swift
> +                fallthrough
Please fix this one as well.

2021-04-23 20:35 UTC, billzhou0223 requested changes

2021-04-23 20:35 UTC, billzhou0223 commented on Apps/Examples/Examples.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 13.5;
Can you also revert the ios target change?

2021-04-23 20:35 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/DataTable/DataTableExample.swift
> +        var view = DataTableView(model: self.model)
Let's just call it `DataTable`. If you take a look at how Apple names components (`List`, `LazyVGrid`, etc), they usually don't put word `View` as a suffix in the name.

2021-04-23 20:46 UTC, ShawnMa16 commented on Apps/Examples/Examples.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 13.5;
this is outdated, it reverted already

2021-04-23 20:49 UTC, billzhou0223 approved these changes

2021-04-23 21:40 UTC, merged