[JIRA: HCPSDKFIORIUIKIT-1897] Signature Form Cell
SAP/cloud-sdk-ios-fiori pull request #212
Opened 2021-03-04 17:52 UTC by fredsap

2021-03-04 19:44 UTC, billzhou0223 requested changes

2021-03-04 19:44 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureView.swift
> +}
Since SwiftUI views are lightweight and fast to initialize, there is no need to store the view like this. 

I am also not sure what the point is to use VStack here given that you only have one subview in the body.

```
struct SignatureView_Example: View {
    var body: some View {
        SignatureView()
    }
}

```

2021-03-04 19:44 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureViewInline.swift
> +struct SignatureViewInline_Example: View {
Same here

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +extension SignatureViewInline {
I am still debating whether using Combine publisher or other patterns like closure or binding is better. Let me think about it. For now we can keep it as is.

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +    @State private var isSignatureEditable = false
This name is confusing. Maybe `isEditing` is more clear.

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureView.swift
> +public struct SignatureView: View {
For `SignatureView`, we need to have an api the same as `SignatureInlineView` to expose saved image to developer.

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +    public var backgroundColor: Color
Any reason these are var instead of let?

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +extension SignatureViewInline {
Model should be public.

2021-03-04 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +    public init(strokeWidth: CGFloat = 3.0, imageStrokeColor: Color = Color.preferredColor(.primaryLabel), backgroundColor: Color = Color.preferredColor(.primaryBackground)) {
Init should take model as a parameter.

2021-03-04 19:53 UTC, billzhou0223 requested changes
Please check the error details for failed CI jobs and fix them.

2021-03-05 22:40 UTC, fredsap commented
Hi Marco, can you take a look at these checks to see if any of them need to be fixed? I've already tried fixing codeformattingcheck and conventionalcommit checks but they keep giving me the same error.

2021-03-05 22:54 UTC, MarcoEidinger commented
- conventionalcommit-verification: **ok** as we should quash and merge this PR to a single commit and the person who will merge it then can give a correct commit message.
  - fyi: once a PR includes a commit which does not follow the conventional commit spec then there will be an error
- PR build failure when using Xcode 11.6: *ok** for me as build on Xcode 11.7 works and I believe most developers are using Xcode 12.x anyway.
  - @billzhou0223 also ok from your side
- sonar: **ok** please ignore for now. I'll work on that

@fredsap only CodeFormattingCheck should be fixed or will subsequent `swiftformat .` will always change the code? Can you test locally?

2021-03-06 00:06 UTC, billzhou0223 commented
> * conventionalcommit-verification: **ok** as we should quash and merge this PR to a single commit and the person who will merge it then can give a correct commit message.
>   
>   * fyi: once a PR includes a commit which does not follow the conventional commit spec then there will be an error
> * PR build failure when using Xcode 11.6: _ok_* for me as build on Xcode 11.7 works and I believe most developers are using Xcode 12.x anyway.
>   
>   * @billzhou0223 also ok from your side
> * sonar: **ok** please ignore for now. I'll work on that
> 
> @fredsap only CodeFormattingCheck should be fixed or will subsequent `swiftformat .` will always change the code? Can you test locally?

@MarcoEidinger SwiftFormatter should run automatically when creating commit right?
@fredsap Let's try to get code format correct first. Like Marco said we can ignore other three check failures for now.

2021-03-06 00:30 UTC, MarcoEidinger commented
> @MarcoEidinger SwiftFormatter should run automatically when creating commit right?

if the latest git commit hooks were installed via `setupForCollaboraters.sh` by the maintainer then yes @billzhou0223 

> @fredsap Let's try to get code format correct first. Like Marco said we can ignore other three check failures for now.

@fredsap as I wrote in a personal Slack message you have to correct markdown comment for `SignatureViewInline` by hand as otherwise `swiftformat` will always change the position of the `*/`

2021-03-08 19:31 UTC, fredsap commented
swift formatting checks fixed

2021-03-08 21:22 UTC, billzhou0223 requested changes

2021-03-08 21:22 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureView.swift
> +    public init(strokeWidth: CGFloat = 3.0, imageStrokeColor: Color = Color.preferredColor(.primaryLabel), backgroundColor: Color = Color.preferredColor(.primaryBackground), model: Model = Model()) {
Adding a model just for signatureImage is weird. Let's use closure to handle the user action for save and image. I have already discussed this with @justinguo last week.

```
public init(..., onSave: (Image) -> Void, onCancel: () -> Void)
```

2021-03-09 00:16 UTC, fredsap commented on Sources/FioriSwiftUICore/SignatureView/SignatureView.swift
> +    public init(strokeWidth: CGFloat = 3.0, imageStrokeColor: Color = Color.preferredColor(.primaryLabel), backgroundColor: Color = Color.preferredColor(.primaryBackground), model: Model = Model()) {
done

2021-03-09 01:04 UTC, billzhou0223 requested changes

2021-03-09 01:04 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureInlineView.swift
> +public struct SignatureViewInline: View {
The name of InlineSignature here is not appropriate any more because it now supports dynamic size. We should rename it to `SignatureCaptureView` for better describing its main functionality.

In SAPFiori, the name `FUISignatureInlineFormCell` is still valid.

2021-03-09 21:33 UTC, justinguo commented
@fredsap Could you confirm that all review comments are addressed?

2021-03-09 22:43 UTC, billzhou0223 approved these changes

2021-03-09 22:51 UTC, billzhou0223 commented
@MarcoEidinger Can you merge this one cause I don't have permission to force merge it.

2021-03-09 23:51 UTC, merged