feat: 🎸 Welcome Screen
SAP/cloud-sdk-ios-fiori pull request #214
Opened 2021-03-10 23:02 UTC by xiaoqinggrace

Initial basic Welcome screen

2021-03-10 23:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/cloud-sdk-ios-fiori?pullRequest=214) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/cloud-sdk-ios-fiori?pullRequest=214) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/cloud-sdk-ios-fiori?pullRequest=214) it.</sub>

2021-03-16 16:03 UTC, MarcoEidinger requested changes
Hi, I propose to have more generic components

2021-03-16 16:03 UTC, MarcoEidinger commented on Sources/FioriSwiftUICore/Views/WelcomeScreen+View.swift
> +            actionTitle
This is based on an existing single property

```swif
internal struct _Component: _ComponentGenerating {
    let actionTitle_: String?
}
```

but this should rather be a `FootnoteAction` component with action handler capabilities (i.e. a `MultiPropertyComponent`). If there is the need to handle welcomeScreen-specific default logic (e.g. open a URL if no developer-defined actionHandler was passed) then this could either be wrapped or become a `WelcomeScreenFootnoteAction` component

2021-03-17 18:55 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Components/MultiPropertyComponents.swift
> +internal protocol _welcomeScreenButton: _ComponentMultiPropGenerating {
It makes sense to me.

2021-03-17 19:28 UTC, billzhou0223 requested changes
I noticed there are some indentation problems in generated files. I assume they should be fixed after we enable swiftformatter.

2021-03-17 19:28 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/WelcomeScreenSample.swift
> +    var title_: String {
Usually we declare it as stored property instead of computed property.

```
let title_: String = "SAP Project Companion for Managers"
```

2021-03-17 19:28 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/WelcomeScreen+View.swift
> +            actionTitle
As oppose to `primaryAction`, we can name it `secondaryAction`.

2021-03-19 18:45 UTC, billzhou0223 requested changes

2021-03-19 18:45 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ActivationScreen+View.swift
> +                print("Email onEditingChanged - \(changed)")
We should remove print statement in production code.

2021-03-19 18:45 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/PrimaryAction+View.swift
> +            Text(self._primaryActionLabel ?? "Start")
Hardcoded text needs to be localized.

2021-03-19 18:45 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SecondaryAction+View.swift
> +            Text(self._secondaryActionText ?? "Try Demo")
Use localized string.

2021-03-19 18:45 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/Components/Component+Protocols.generated.swift
> +    var secondaryActionText_: String? { get }
We should use same naming convention for both primary and secondary action.

`secondaryActionLabel_`

2021-03-19 18:45 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/ActivationScreenSample.swift
> +            ActivationScreen(title: model.title_, descriptionText: model.descriptionText_, subtitle: model.subtitle_, primaryActionLabel: model.primaryActionLabel_, footnote: model.footnote_, seconda
Usually we don't put the type in the name so I would suggest change param name from `didSelectPrimaryActionClosure` to `didSelectPrimaryAction`. Same for secondary action.

2021-03-19 18:45 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ActivityItem+View.generated.swift
> -//TODO: Implement LibraryContentProvider
I think we should keep these `LibraryContentProvider` related changes. @MarcoEidinger Please comment.

2021-03-19 18:49 UTC, billzhou0223 commented
@xiaoqinggrace I recommend creating a new PR for new component next time. It also helps when generating change log.

2021-03-22 00:40 UTC, xiaoqinggrace commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/ActivationScreenSample.swift
> +            ActivationScreen(title: model.title_, descriptionText: model.descriptionText_, subtitle: model.subtitle_, primaryActionLabel: model.primaryActionLabel_, footnote: model.footnote_, seconda
The name didSelectPrimaryActionClosure is generated. @MarcoEidinger

2021-03-22 17:10 UTC, MarcoEidinger commented on Sources/FioriSwiftUICore/_generated/ViewModels/Boilerplate/ActivityItem+View.generated.swift
> -//TODO: Implement LibraryContentProvider
@billzhou0223 correct.

@xiaoqinggrace: I believe you have not rebased the latest code. Then this should not be removed (unless you modified it)

2021-03-22 17:19 UTC, MarcoEidinger commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/ActivationScreenSample.swift
> +            ActivationScreen(title: model.title_, descriptionText: model.descriptionText_, subtitle: model.subtitle_, primaryActionLabel: model.primaryActionLabel_, footnote: model.footnote_, seconda
@billzhou0223 the `Closure` addition comes from our code generation as @xiaoqinggrace pointed out correctly.

https://github.com/SAP/cloud-sdk-ios-fiori/blob/033f547866628c9bb0352fe5dfec12ec25260c6a/sourcery/.lib/Sources/utils/Type%2BExtensions.swift#L158 

I'll provide a PR to omit the addition. This PR you can review/approve and then @xiaoqinggrace can rebase and re-generate her code

2021-03-25 00:36 UTC, justinguo commented
@billzhou0223 @xiaoqinggrace One question here: In current design of onboarding screens, we need to add a blended header view (in most updated design we changed it from a `UIVisualEffectView` to `UIView` for UIKit, and it has the same height of the nav bar) below the status bar. Have we consider how to handle this use case in SwiftUI?

2021-03-26 16:19 UTC, MarcoEidinger requested changes
Seems that the pull request is not based and generated based on the latest `migration` branch code as I see generated code which should be there if https://github.com/SAP/cloud-sdk-ios-fiori/pull/220/ is present

Are there any functional leftovers? I see commented code...

2021-03-26 16:19 UTC, MarcoEidinger commented on Sources/FioriSwiftUICore/Views/ActivationScreen+View.swift
> +//                    })
Is this a TODO ?

2021-03-26 16:19 UTC, MarcoEidinger commented on sourcery/.lib/Sources/utils/Variable+Extensions.swift.modified
> +import Foundation
File to be removed!

2021-03-26 16:55 UTC, xiaoqinggrace commented on sourcery/.lib/Sources/utils/Variable+Extensions.swift.modified
> +import Foundation
I did not add any files in sourcery to the staged list. I don't know how it checked in. I will reverse the change.

2021-03-26 23:55 UTC, billzhou0223 requested changes
`LibraryContentProvider` shouldn't be removed.

CI build failure needs to be resolved as well.

2021-03-29 23:03 UTC, billzhou0223 approved these changes

2021-03-29 23:04 UTC, merged