Support both UIImage and Image types in Signature View
SAP/cloud-sdk-ios-fiori pull request #226
Opened 2021-03-29 20:39 UTC by fredsap

2021-03-29 20:52 UTC, justinguo commented
@fredsap Could you check and fix the comments from hound? Also could you fix the conflicts with main branch?

2021-03-29 22:48 UTC, billzhou0223 reviewed
I have a new proposal. Instead of having two closures to pass Image and UIImage which might be a little confusing. We can create a result struct to wrap them up. And pass this result to `onSave` handler. @justinguo Please let me know how you like this idea.

```
extension SignatureCaptureView {
  public struct Result {
    let image: Image
    let uiImage: UIImage
  }
}
```

2021-03-30 00:03 UTC, justinguo commented
> I have a new proposal. Instead of having two closures to pass Image and UIImage which might be a little confusing. We can create a result struct to wrap them up. And pass this result to `onSave` handler. @justinguo Please let me know how you like this idea.
> 
> ```
> extension SignatureCaptureView {
>   public struct Result {
>     let image: Image
>     let uiImage: UIImage
>   }
> }
> ```

This looks good to me. @fredsap Could you adopt this solution for now? Also please clean up unused code for conversion between `UIImage` and `Image` (if any).

2021-03-30 21:38 UTC, justinguo commented on Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
>      func snapshot() -> UIImage {
@fredsap Are we using this extension method currently? If not we can remove it for now.

2021-03-30 21:40 UTC, justinguo commented on Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
>      }
@fredsap Same here.

2021-03-30 22:57 UTC, justinguo commented
@billzhou0223 In general this looks fine to me as of now. Do you think this is fine?

2021-03-30 22:59 UTC, billzhou0223 requested changes

2021-03-30 22:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
> +public struct Result {
I suggest making it a nested type of SignatureCaptureView. Otherwise you need to rename it to be more specific instead of calling it Result.

```
extension SignatureCaptureView {
  public struct Result {}
}
```

2021-03-30 23:04 UTC, fredsap commented on Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
> +public struct Result {
cant because drawing pad needs result

2021-03-30 23:10 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/SignatureHelper.swift
> +public struct Result {
What do you mean? It's just a type under SignatureCaptureView `SignatureCaptureView.Result`

2021-03-31 18:04 UTC, justinguo approved these changes
Looks good now. @billzhou0223 Do you think this looks fine now?

2021-03-31 21:00 UTC, billzhou0223 approved these changes

2021-03-31 21:02 UTC, merged