feat: 🎸 ObjectItem
SAP/cloud-sdk-ios-fiori pull request #227
Opened 2021-03-30 21:55 UTC by shengxu7

2021-03-30 22:54 UTC, billzhou0223 requested changes
I recommend adding doc for public apis next time before creating PR.

2021-03-30 22:54 UTC, billzhou0223 commented on Package.swift
> +        .library(
Let's revert this change.

2021-03-31 00:14 UTC, shengxu7 commented on Package.swift
> +        .library(
Reverted.

2021-03-31 00:23 UTC, billzhou0223 approved these changes

2021-03-31 17:08 UTC, MarcoEidinger approved these changes

2021-03-31 17:08 UTC, merged