fix: 🐛 Fix border and multi-gesture issues in Signature View
SAP/cloud-sdk-ios-fiori pull request #231
Opened 2021-04-05 23:02 UTC by fredsap

2021-04-06 00:24 UTC, billzhou0223 requested changes
Instead of hard coding the value, can we create a property in the drawing pad for the margin and use it in calculation. This makes it easier if we need to adjust the margin in the future. 

```
struct DrawingPad {
    let padding: EdgeInset
}
```

2021-04-06 22:26 UTC, billzhou0223 requested changes

2021-04-06 22:26 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/SignatureView/DrawingPad.swift
> +    let signaturePadding: CGFloat = 20
Any reason you use `CGFloat` here which only provides one single value for padding on four edges.

What if we want the padding to be different on different edges? That's why I suggest using `EdgeInsets` in last comment.

2021-04-06 23:49 UTC, fredsap commented on Sources/FioriSwiftUICore/SignatureView/DrawingPad.swift
> +    let signaturePadding: CGFloat = 20
I see your point, but there's really isn't any way to make the padding different on different edges. That will mean different and specific calculations for the signature origin.

2021-04-08 00:18 UTC, billzhou0223 approved these changes

2021-04-08 00:19 UTC, merged