feat: 🎸 InfoView
SAP/cloud-sdk-ios-fiori pull request #242
Opened 2021-04-13 18:17 UTC by xiaoqinggrace

Add InfoView. Modify the binding in ActivationScreen.

2021-04-22 01:20 UTC, billzhou0223 requested changes
Ideally we don't want to include WelcomeScreen changes in this PR because this one is for InfoView. 

No need to worry about it this time but we should try to avoid this in the future.

2021-04-22 01:20 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/InfoView+View.swift
> +                    .frame(width: 169.0, height: 20.0)
We want the frame of action button to be dynamic so probably set framework with `minWidth` and `minHeight` makes more sense.

2021-04-22 01:20 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/InfoView+View.swift
> +//            }
Let's clean up these commented code to make our code base cleaner.

2021-04-22 01:20 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/WelcomeScreen+View.swift
> +                .disableAutocorrection(true)
Should these styles be set in textFilled's default view modifier?

2021-04-22 05:29 UTC, xiaoqinggrace commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/ActivationScreenSample.swift
> +        )
It is for updating the parameter to be used in the didSelectAction(). We can sync in Slack.

2021-04-22 05:33 UTC, xiaoqinggrace commented on Apps/Examples/Examples/FioriSwiftUICore/Onboarding/ActivationScreenSample.swift
> +            ActivationScreen(title: model.title_, descriptionText: model.descriptionText_, textFilled: binding, actionText: model.actionText_, footnote: model.footnote_, secondaryActionText: model.se
The reason to use the current method for creation is due to the binding value textFilled: binding.

2021-04-23 20:58 UTC, billzhou0223 submitted a review, later dismissed

2021-06-07 22:56 UTC, billzhou0223 commented
Resolved by #283

2021-06-07 22:56 UTC, closed without merging