Data table inline editing
SAP/cloud-sdk-ios-fiori pull request #321
Opened 2021-09-17 00:38 UTC by ShawnMa16

2021-09-17 05:43 UTC, billzhou0223 requested changes
One question need to be clarified by designer: How the picker should be presented in regular mode? Still a bottom sheet or a model sheet in the center of view?

2021-09-17 05:43 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/ItemView.swift
> +    func setKeyboardNotifications() {
The notification added by `addObserver` needs to be removed at some point when the view is destroyed. 

In SwiftUI there might be a better alternative solution to add notification. See the post: https://stackoverflow.com/questions/61822307/how-to-remove-observer-in-swiftui

2021-09-17 05:43 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/ItemView.swift
> +                    .stroke(Color.blue.opacity(self.isDetectingLongPress ? 1 : (self.inlineEditing ? 1 : 0)), lineWidth: 2)
All the colors used in component need to be Fiori Color `Color.preferredColor()`

2021-09-17 05:43 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/MultiPicker.swift
> +                        Text("Done")
Hard coded text needs to be localized.

2021-09-17 05:43 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/TableModel.swift
> +    @Published public var inlineEditingEable: Bool = true
typo.

I will remove this property in table model and add a `isEditable` property in `DataItem`.

2021-09-21 00:16 UTC, ShawnMa16 commented on Sources/FioriSwiftUICore/DataTable/DataTextItem.swift
> +public class DataTextItem: DataItem, CheckBinding {
I made this change due to the in place editing feature

2021-12-09 16:57 UTC, MarcoEidinger commented
@billzhou0223  can this PR be closed (without merge) ?

2021-12-14 01:28 UTC, billzhou0223 commented
Not needed anymore.

2021-12-14 01:28 UTC, closed without merging