refactor: 💡 User Consent Form
SAP/cloud-sdk-ios-fiori pull request #377
Opened 2021-11-18 19:50 UTC by xiaoqinggrace

Refactor User Consent Form samples based on the Composite component
generation (Sourcery)

2021-11-19 19:43 UTC, billzhou0223 requested changes
Please resolve CI build issues first.

2021-12-01 23:40 UTC, billzhou0223 requested changes
Please schedule a meeting with me to go through the changes in this PR.

2021-12-01 23:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentForm+View.swift
> +            }
check

2021-12-01 23:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentForm+View.swift
> +                            }
check

2021-12-01 23:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentForm+View.swift
> +            }
check

2021-12-01 23:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentView+View.swift
> +//                self._didFinish?(_allowedFormIndexes)
check

2021-12-15 21:00 UTC, billzhou0223 requested changes

2021-12-15 21:01 UTC, billzhou0223 requested changes
Also please update the table in the readme to mark this component as completed.

2021-12-16 08:33 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentView+View.swift
> +//                self._didFinish?(_allowedFormIndexes)
We should not put it back since it will cause the user consent form to go back to two levels when the user clicks on cancel -> quit.

2021-12-16 20:01 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/UserConsentView/UserConsentView+View.swift
> +//                self._didFinish?(_allowedFormIndexes)
The issue is from test app in fact. We should only call dismiss in `didFinish`. Logically cancel action should still lead to the finish of the flow.

2021-12-16 20:51 UTC, billzhou0223 approved these changes

2021-12-16 20:51 UTC, merged