fix: [HCPSDKFIORIUIKIT-2043] resolve UIFont instance from Swift pass to SwiftUI can't be resized and empty text disable accessibility.
SAP/cloud-sdk-ios-fiori pull request #418
Opened 2022-04-20 07:51 UTC by AllenCao001

2022-04-20 20:17 UTC, billzhou0223 requested changes
@shengxu7

2022-04-20 20:17 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTable/LayoutData.swift
> +                    if let styleName = tmpUIFont.fontDescriptor.fontAttributes[.textStyle] as? String {
In order for the text to be resizable, developes are responsible for passing in a scaled font. We, as SDK, are not supposed to force this conversion.

2022-04-21 00:35 UTC, shengxu7 approved these changes

2022-04-21 01:35 UTC, AllenCao001 commented on Sources/FioriSwiftUICore/DataTable/LayoutData.swift
> +                    if let styleName = tmpUIFont.fontDescriptor.fontAttributes[.textStyle] as? String {
At now, the issue is developers had init a `UIFont` instance via `UIFont.preferredFont()` in SDK and passed it to SwiftUI, but the text doesn't be resizable in SwiftUI. In order to fix the issue, so need to redefine `UIFont` in SwiftUI, it is as the above code.

2022-04-21 22:39 UTC, billzhou0223 approved these changes

2022-04-25 03:30 UTC, AllenCao001 commented
When it can be merged into the main branch? Whether this pull request has any question? Because I need to fix the issue-2043.

2022-04-25 17:14 UTC, merged