feat:[JIRA:HCPSDKFIORIUIKIT-2180] Chart Color updates
SAP/cloud-sdk-ios-fiori pull request #446
Opened 2022-07-27 01:28 UTC by KevinZK

2022-07-27 20:39 UTC, billzhou0223 requested changes
Need to double check and fix all the mapping issues.

2022-07-27 20:39 UTC, billzhou0223 commented on Sources/FioriThemeManager/Colors/ColorStyle.swift
> +    /// (dark variant) ![](https://dummyimage.com/48x18/4DB1FF.png&text=+)          Hex value: 4DB1FF
The mapping is wrong. `5899DA` should be mapped to `1B90FF`.

2022-07-27 20:40 UTC, billzhou0223 commented
You need to sign the CLA first.

2022-07-29 21:37 UTC, dyongxu commented
@KevinZK Your new colors did not replace the correct value based on the mode (light or dark).   Currently the order of "light / dark" color is reversed.
To avoid this, e.g. you can simply replace the value of E8743B to E76500 for chart2, so it won't go to the wrong location.

2022-08-03 01:15 UTC, billzhou0223 approved these changes

2022-08-03 22:04 UTC, merged