feat: 🎸 a searchable list picker
SAP/cloud-sdk-ios-fiori pull request #471
Opened 2022-10-18 02:51 UTC by xiaoyu0722

A searchable list picker that support tracking alive or not.

2022-10-19 20:26 UTC, billzhou0223 requested changes

2022-10-19 20:26 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +         isTrackingLive: Bool,
Rename to `isTrackingLiveChanges`

2022-10-19 20:26 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
1. Does your component support multi-level selection?
2. How can developers provide their own search criteria? (closure based)

2022-10-20 07:25 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
Currently, spec does not need multi-level selection, and I will double confirm with spec owner.
And for search criteria, I added a new `keypath` for filter data.

2022-10-20 18:49 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
The current implementation of ListPickerItem already supports multi-level selection. We can add search on top of it instead of aborting this existing feature.

Search criteria is not just a keypath, it may involve control flow and some logic. We should let developers pass list picker a callback so that we can use it to filter the dataset. The usage code could be something like:

```
ListPickerItem(data) { searchString, item in
    return item.name.contains(searchString)
}
```

2022-10-21 03:03 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
```swift
public init<Data, ID, RowContent>(_ data: Data,
                                  id: KeyPath<Data.Element, ID>,
                                  children: KeyPath<Data.Element, Data?>?,
                                  selection: Binding<Set<ID>>?,
                                  isTrackingLiveChanges: Bool = false,
                                  criteria: @escaping (Data.Element, String) -> Bool,
                                  @ViewBuilder rowContent: @escaping (Data.Element) -> RowContent)
```
A criteria closure is required for searchable `ListPickerItemConfiguration`
Also an optional children is also provided, but currently, the search bar is separately for each level list.
The sublist will tracking changes, that developer only can confirm/cancel the changes at root list.
Spec is not ready for multi-level support, double confirmed with the spec owner(only single-level is required). Multi-level support may not be the final version.

2022-10-25 00:57 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
As a SDK component it ought to be extendable and we need to plan for requirement changes. Multi-level picker is very useful and we had customers ask for it back in the days. So it's nice if we provide it as an option.

Regarding to cancel/confirm action, that's a little tricky because we need to somehow store the selections temporarily until users confirm the selection or discard the changes if users cancel it at the top level. I feel this might require changes in the current architecture of list picker. I need to do some experiments on my side. In the meanwhile you can also think about it.

2022-10-26 22:15 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
I did some experiments. The search and confirm/cancel now works with multi-level selection. You may want to take a look and start from there.

2022-10-27 08:50 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
Emm, I see your branch.
Current implementation use `isTrackingAlive` instead of `isTopLevel` for the condition to show cancel/confirm actions.
```swift
if isTrackingAlive == true {
  no cancel/confirm actions
} else {
  show cancel/confirm actions
  use selections buffer
  and force tracking buffer alive.(no actions for the sub list actions)
  update selections by buffer once confirm tapped.
}
```
So same implementation?

2022-10-27 23:23 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
I don't think `isTrackingLiveChanges` should be tied to confirm/cancel logic. The selection binding property should only be updated when confirm is triggered. 

If you want to make `isTrackingLiveChanges` useful, you can add a callback or publisher which notifies the receiver whenever the selection changes. Do not add the interim changes into selection binding property since it is only for storing the final result.

2022-10-27 23:23 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
`isTopLevel` is for internal use only. It's not visible to developers.

2022-10-28 02:26 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct ListPickerSearchableView<Data: RandomAccessCollection,
Got it, I remove the `isTrackingChangesAlive` first. I'm not sure if this will effect the actions.

2022-11-02 17:13 UTC, billzhou0223 requested changes

2022-11-03 00:54 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +        self.destinationView = ListPickerSearchableView(data: data,
fixed.

2022-11-03 19:10 UTC, billzhou0223 approved these changes

2022-11-07 03:06 UTC, xiaoyu0722 commented
`Testing failed:
	Value of type 'List<Never, ForEach<[Data.Element], ID, _ConditionalContent<ListPickerItem<RowContent, EmptyView>, ListPickerItem<RowContent, EmptyView>.Row<ID>>>>' has no member 'searchable'
`
`searchable` is not imported in Xcode 12. Is this job essential?

2022-11-10 15:50 UTC, dyongxu commented
All checks passed. Merged this PR.

2022-11-10 15:51 UTC, merged