fix:[BCP:2270157767] deprecated chart 7and chart 11
SAP/cloud-sdk-ios-fiori pull request #483
Opened 2022-11-11 09:04 UTC by KevinZK

2022-11-14 04:20 UTC, dyongxu approved these changes

2022-11-14 23:57 UTC, billzhou0223 requested changes

2022-11-14 23:57 UTC, billzhou0223 commented on Sources/FioriThemeManager/Colors/ColorStyle.swift
> +    @available(*, unavailable, message: "")
We definitely cannot simply make it unavailable in `ColorStyle` because it is still used by the old palettes. Deprecation is not good as well for the same reason.

Suggestion:
1. Add a note in head doc to indicate its status (See example below).
2. Add a new palette (V8) and remove `chart10` and `chart11` from its definition. Do not touch old palletes.
3. Make sure the removed colors are mapped to other colors correctly. Refer to this [doc](https://github.wdf.sap.corp/I862313/Fiori-UI-Knowledge-Sharing/blob/master/ThemeManager/Theme%20Manager.md) for how to implement it.

```
/// Chart 10
/// (dark variant) ![](https://dummyimage.com/48x18/EE3939.png&text=+)          Hex value: EE3939
/// (light variant) ![](https://dummyimage.com/48x18/FF5C77.png&text=+)          Hex value: FF5C77
///
/// - Note: Removed since Palette V8. Mapping to `chart1`.
case chart10
```

I use `chart1` here just for demonstration. You need to ask designers what color the removed one should map to.

2022-11-16 09:19 UTC, KevinZK commented
do not merge yet

2022-11-16 09:19 UTC, closed without merging