feat: 🎸 [JIRA-2222] Duration Picker Support
SAP/cloud-sdk-ios-fiori pull request #484
Opened 2022-11-14 08:36 UTC by xiaoyu0722

FUIDurationPickerFormCell SwiftUI migration
**Public API**
```swift
public init(selection: Binding<Int>, maximumMinutes: Int = 1439, minimumMinutes: Int = 0, minuteInterval: Int = 1, measurementFormatter: MeasurementFormatter = MeasurementFormatter())
```
- selection: Binding<Int>
   A minutes binding for picker selection.
- maximumMinutes: Int
   Maximum minutes picker allowed, maximum is 1439.
- minimumMinutes: Int
   Minimum minutes picker allowed, minimum is 0.
- minuteInterval: Int
   Interval for minutes.
- measurementFormatter: MeasurementFormatter
  Formatter for picker titles.
  
```swift
/// Measurement formatter for duration picker.
/// - Parameter measurementFormatter: measurement formatter you wanted for picker titles.
/// - Returns: return a new duration picker with the measurement formatter.
public func measurementFormatter(_ measurementFormatter: MeasurementFormatter) -> Self

2022-11-30 19:28 UTC, billzhou0223 requested changes
Please resolve the conflicts.

2022-11-30 19:28 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DurationPicker/DurationPickerViewWrapper.swift
> +struct DurationPickerViewWrapper: UIViewRepresentable {
I remember we discussed last time to avoid using UIKit controls if possible?

2022-12-01 02:28 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/DurationPicker/DurationPickerViewWrapper.swift
> +struct DurationPickerViewWrapper: UIViewRepresentable {
I tried, SwiftUI `Picker` can't support the spec style.

2022-12-01 23:28 UTC, billzhou0223 approved these changes

2022-12-01 23:28 UTC, merged