fix:[BCP:2270157767] deprecated chart 10 and chart 11
SAP/cloud-sdk-ios-fiori pull request #490
Opened 2022-11-17 05:57 UTC by KevinZK

2022-11-18 01:00 UTC, billzhou0223 requested changes

2022-11-22 00:10 UTC, billzhou0223 commented on Sources/FioriThemeManager/Colors/ColorStyle.swift
> +    @available(*, deprecated, message: "")
Did you resolve this issue? 

I have discussed with David, let's add a note in the head doc to tell in which palette the style is removed instead of using deprecation syntax.

2022-11-22 01:34 UTC, KevinZK commented on Sources/FioriThemeManager/Colors/ColorStyle.swift
> +    @available(*, deprecated, message: "")
Solved

2022-11-22 22:38 UTC, billzhou0223 approved these changes

2022-11-23 23:07 UTC, merged