feat: 🎸 [JIRA: 2219] List picker with single selection
SAP/cloud-sdk-ios-fiori pull request #491
Opened 2022-11-17 08:05 UTC by xiaoyu0722

Support single selection and allow empty filter condition.

https://user-images.githubusercontent.com/2142582/202390450-9ab3ba2c-c5e6-4de7-b64a-5c8e9bc177ba.mp4

2022-11-17 19:38 UTC, billzhou0223 requested changes

2022-11-17 19:38 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
>                                        searchFilter: @escaping (Data.Element, String) -> Bool,
The search filter parameter should be optional.

2022-11-18 01:11 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
>                                        searchFilter: @escaping (Data.Element, String) -> Bool,
Fixed.

2022-11-18 19:49 UTC, billzhou0223 approved these changes

2022-11-22 00:05 UTC, merged