fix: 🐛 fiori theme updates for multiple components
SAP/cloud-sdk-ios-fiori pull request #526
Opened 2023-02-23 02:33 UTC by xiaoyu0722

HCPSDKFIORIUIKIT-2245 HCPSDKFIORIUIKIT-2257 HCPSDKFIORIUIKIT-2258 
HCPSDKFIORIUIKIT-2262 HCPSDKFIORIUIKIT-2264

2023-02-23 23:24 UTC, billzhou0223 requested changes

2023-02-23 23:24 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SearchableListContent.swift
> +                    UITableView.appearance().backgroundColor = UIColor.preferredColor(.secondaryBackground)
Use `UIColor.preferredFioriColor`

2023-02-23 23:24 UTC, billzhou0223 commented on Sources/FioriThemeManager/Colors/UIColor+Extension.swift
> +    static func preferredColor(_ style: ColorStyle, background scheme: BackgroundColorScheme? = .device, interface level: InterfaceLevel? = .device, display mode: ColorDisplayMode? = .device) -> UICo
Can we make it internal?

Rename to `preferredFioriColor`

2023-02-23 23:24 UTC, billzhou0223 commented on Sources/FioriThemeManager/72-Fonts/UIFont+Fiori.swift
> +public extension UIFont {
Sheng already add this in #525.

2023-02-24 19:01 UTC, billzhou0223 requested changes

2023-02-27 01:28 UTC, xiaoyu0722 commented on Sources/FioriThemeManager/Colors/UIColor+Extension.swift
> +public extension UIColor {
But, `ThemeManager.shared.uiColor` is internal in `FioriThemeManager` module.
I need a public api, so I can call it in `FioriSwiftUICore`.

2023-02-28 20:12 UTC, billzhou0223 requested changes

2023-02-28 20:12 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SearchableListContent.swift
> +                    UITableView.appearance().backgroundColor = Color.preferredColor(.secondaryBackground).uiColor()
Not sure if color created like this is dynamic color.

Another option is to use `Color.preferredUIColor()`

2023-03-01 01:12 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/SearchableListContent.swift
> +                    UITableView.appearance().backgroundColor = Color.preferredColor(.secondaryBackground).uiColor()
Yes, its dynamic. `preferredColor` and `preferredUIColor` are using same implementation.
``` swift
internal func color(for style: ColorStyle, background scheme: BackgroundColorScheme?, interface level: InterfaceLevel?, display mode: ColorDisplayMode?) -> Color {
    let uiColor = self.uiColor(for: style, background: scheme, interface: level, display: mode)
    let color = Color(uiColor)
    return color
}

2023-03-01 01:20 UTC, billzhou0223 approved these changes

2023-03-02 01:06 UTC, closed without merging

2023-03-02 01:06 UTC, xiaoyu0722 commented
All commits in #530