feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2224] New FioriButtonStyle support
SAP/cloud-sdk-ios-fiori pull request #603
Opened 2023-10-16 19:46 UTC by billzhou0223

2023-10-18 16:35 UTC, janhuachu approved these changes

2023-10-18 16:35 UTC, janhuachu commented
Should we let Andy review the header docs?

2023-10-19 20:42 UTC, AndyRogersSAP requested changes
UA Review. Please see inline edits, comments, and questions.

I assume that "Fiori" should be capitalized so have changed all instances of "fiori" to "Fiori."

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +/// ## Create a fiori button by providing an action and different labels depending on states.
```suggestion
/// ## Create a Fiori button by providing an action and different labels depending on states.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +/// ## Create a fiori button with title text.
```suggestion
/// ## Create a Fiori button with title text.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +/// Create a style that conforms to `FioriButtonStyle`. There are three pre-defined fiori button styles: `FioriPrimaryButtonStyle`, `FioriSecondaryButtonStyle` and `FioriTertiaryButtonStyle`. To set
```suggestion
/// Create a style that conforms to `FioriButtonStyle`. There are three predefined Fiori button styles: `FioriPrimaryButtonStyle`, `FioriSecondaryButtonStyle`, and `FioriTertiaryButtonStyle`. To set the style to a `FioriButton` or to a container within which all Fiori buttons should share the same style, use the `fioriButtonStyle(_:)` modifier.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +///  To apply these styles to a `Button`, use `PrimaryButtonStyle`, `SecondaryButtonStyle` and `TertiaryButtonStyle` instead.
```suggestion
///  To apply these styles to a `Button`, use `PrimaryButtonStyle`, `SecondaryButtonStyle`, and `TertiaryButtonStyle` instead.
```
I think you can safely delete the word "instead." It's not really necessary.

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// Creates a view that represents the body of a fiori button.
```suggestion
    /// Creates a view that represents the body of a Fiori button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// The system calls this method for each ``FioriButton`` instance in a view
Is there a reason to use double backticks?

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// - Parameter configuration : The properties of the fiori button.
```suggestion
    /// - Parameter configuration: The properties of the Fiori button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// The properties of a fiori button.
```suggestion
    /// The properties of a Fiori button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// Return a type-erased fiori button style.
```suggestion
    /// Return a type-erased Fiori button style.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// - Returns: An AnyFioriButtonStyle wrapping this button style.
```suggestion
    /// - Returns: An `AnyFioriButtonStyle` wrapping this button style.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +/// The properties of a fiori button.
```suggestion
/// The properties of a Fiori button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +        /// The content of label.
```suggestion
        /// The content of the label.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// - Parameter state: A valid state for button. For a fiori button with non-persistent selection, `.normal`, `.disabled`, `.highlighted` are supported. For a button with persistent selection, us
```suggestion
    /// - Parameter state: A valid state for a button. For a Fiori button with non-persistent selection, `.normal`, `.disabled`, and `.highlighted` are supported. For a button with persistent selection, use `.selected` instead of `.highlighted`.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +/// A fiori button style for the primary button.
```suggestion
/// A Fiori button style for the primary button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// Create a FioriPrimaryButtonStyle instance.
```suggestion
    /// Create a `FioriPrimaryButtonStyle` instance.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +/// A fiori button style for the secondary button.
```suggestion
/// A Fiori button style for the secondary button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +/// A fiori button style for the tertiary button.
```suggestion
/// A Fiori button style for the tertiary button.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// Sets the style for fiori buttons within this view.
```suggestion
    /// Sets the style for Fiori buttons within this view.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +    /// - Parameter style: A fiori button style instance.
```suggestion
    /// - Parameter style: A Fiori button style instance.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/FioriButtonStyle.swift
> +/// A type-erased fiori button style.
```suggestion
/// A type-erased Fiori button style.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +    /// The system calls this method for each ``Button`` instance in a view
Double backticks?

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +/// An object that provides fiori secondary button style for `Button`.
```suggestion
/// An object that provides the Fiori secondary button style for `Button`.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +    /// The system calls this method for each ``Button`` instance in a view
Double backticks?

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +/// An object that provides fiori tertiary button style for `Button`.
```suggestion
/// An object that provides the Fiori tertiary button style for `Button`.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +    /// The system calls this method for each ``Button`` instance in a view
Double backticks?

2023-10-19 20:42 UTC, AndyRogersSAP commented on Apps/Examples/Examples/FioriSwiftUICore/FioriButton/FioriButtonExample.swift
> +    /// - Returns: An AnyPrimitiveButtonStyle wrapping this button style.
```suggestion
    /// - Returns: An `AnyPrimitiveButtonStyle` wrapping this button style.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
>  /// An object that provides fiori style color and interaction for `Button`.
```suggestion
/// An object that provides Fiori style color and interaction for `Button`.
```

2023-10-19 20:42 UTC, AndyRogersSAP commented on Sources/FioriSwiftUICore/FioriButton/StatefulButtonStyle.swift
> +/// An object that provides fiori primary button style for `Button`.
```suggestion
/// An object that provides Fiori primary button style for `Button`.
```

2023-10-19 23:47 UTC, merged