feat: 🎸 jira 2286 sort & filter for SwiftUI project
SAP/cloud-sdk-ios-fiori pull request #606
Opened 2023-10-19 21:47 UTC by CharlesXu0488

A SwiftUI component for configuration criteria of performing sorting and filter. SortFilterMenu and SortFilterFullCFG are provided.

✅ Closes: 1

2023-11-01 00:40 UTC, billzhou0223 requested changes

2023-11-01 00:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +public protocol SliderPickerModel: SliderPickerComponent {}
Rename to `SliderPickerItemModel`

2023-11-01 00:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +public protocol OptionListPickerModel: OptionListPickerComponent {
We should reuse the existing list picker instead of creating a new one.

2023-11-01 00:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +public protocol SwitchPickerModel: SwitchPickerComponent {}
We used the name PickerItem for other picker controls (e.g. ListPickerItem) so let's keep using it.

 Rename to `SwitchPickerItemModel`

2023-11-01 00:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SortFilter/SortFilterItemTitle.swift
> +public struct SortFilterItemTitle: TitleComponent, View {
Make it internal.

2023-11-01 00:40 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SortFilter/SortFilterStyle.swift
Where is this class used? Please remove it if it's not needed.

2023-11-06 18:31 UTC, CharlesXu0488 commented on Sources/FioriSwiftUICore/Views/SortFilter/SortFilterStyle.swift
removed

2023-11-06 18:32 UTC, CharlesXu0488 commented on Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
> +                SortFilterMenu(items: $items, onUpdate: performSortAndFilter)
fixed

2023-11-06 18:32 UTC, CharlesXu0488 commented on Apps/Examples/Examples/FioriSwiftUICore/SortFilter/SortFilterExample.swift
> +            .switch(item: .init(name: "Favorite", value: true, icon: "heart.fill"), isShownOnMenu: true),
fixed

2023-11-06 18:32 UTC, CharlesXu0488 commented on Sources/FioriSwiftUICore/Views/SortFilter/SortFilterItemTitle.swift
> +public struct SortFilterItemTitle: TitleComponent, View {
removed public

2023-11-06 23:19 UTC, billzhou0223 approved these changes

2023-11-07 00:06 UTC, dyongxu approved these changes

2023-11-07 00:33 UTC, merged