feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2459] Tab Bar
SAP/cloud-sdk-ios-fiori pull request #621
Opened 2023-12-01 08:01 UTC by xiaoyu0722

2023-12-02 04:26 UTC, billzhou0223 reviewed
Do we need to provide default styles for tab bar items similar to what we did for nav bar?

2023-12-04 23:06 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/TabViewExample/TabViewDetailView.swift
> +    @State private var accendColor = Color.orange
Change the color to use Fiori based color

2023-12-04 23:07 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/TabViewExample/TabViewDetailView.swift
> +                UITabBarItem.appearance().setTitleTextAttributes([.font: UIFont.preferredFioriFont(forTextStyle: .title3),
Change the color to use Fiori based color, for the codes in this example.

2023-12-04 23:16 UTC, dyongxu requested changes
1. Try to use Fiori Color , wherever possible
2. Add the support for tab haptic sound. In SDK UIKit, when the user taps the tab, it will have vibration and sound.

2023-12-04 23:18 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/TabViewExample/TabViewDetailView.swift
> +                UITabBarItem.appearance().setTitleTextAttributes([.font: UIFont.preferredFioriFont(forTextStyle: .title3),
There are lots of places using the native color from Apple in this PR. Let's try to switch to Fiori Color as much as possible.

2023-12-05 02:48 UTC, xiaoyu0722 commented
> Do we need to provide default styles for tab bar items similar to what we did for nav bar?

All this setting are for test app, also I will restore to system default setting when view are disappeared.

2023-12-06 19:48 UTC, dyongxu approved these changes

2023-12-06 19:49 UTC, dyongxu commented
> > Do we need to provide default styles for tab bar items similar to what we did for nav bar?
> 
> All these settings are for test app, also I will restore to system default setting when view are disappeared.

Yes, it will be a good idea to use Fiori Color and Font, even if in the TestApp, just to show Fiori Styles can be actually applied.

2023-12-07 01:50 UTC, merged