feat: merge visionOS branch into main
SAP/cloud-sdk-ios-fiori pull request #622
Opened 2023-12-15 23:23 UTC by dyongxu

2023-12-18 09:38 UTC, billzhou0223 approved these changes

2023-12-18 09:48 UTC, billzhou0223 requested changes

2023-12-18 09:48 UTC, billzhou0223 commented on Package@swift-5.9.swift
What's the reason to add this new file rather than updating the existing `package.swift` file?

Usually we just need to update the version number in `package.swift`.

2023-12-18 17:28 UTC, dyongxu commented on Package@swift-5.9.swift
@MarcoEidinger  Shall we merge the contents from Package@swift-5.9.swift to Package.swift?  Looks like , this "new" file is no longer needed in main branch ?

2023-12-18 18:16 UTC, MarcoEidinger commented
@billzhou0223  and @dyongxu : an important question: do you want to expose all modules with their APIs for visionOS even `SAPFioriSwiftUICore` and `SAPFioriCharts` were not optimized and tested? If not, then additional efforts are needed, either excluding modules in `Package.swift` or excluding individual APIs with conditional compilation statements.

2023-12-18 19:27 UTC, dyongxu commented
I am ok with exposing all APIs, with a "disclaimer" that not all UIs for visionOS are optimized for native experience. @MarcoEidinger @billzhou0223

2023-12-19 08:41 UTC, billzhou0223 commented
> I am ok with exposing all APIs, with a "disclaimer" that not all UIs for visionOS are optimized for native experience. @MarcoEidinger @billzhou0223

LGTM.

2023-12-19 16:09 UTC, MarcoEidinger commented
**DO NOT DELETE** visionOS branch as it is still referenced by SAP teams

2023-12-21 01:49 UTC, MarcoEidinger approved these changes

2023-12-21 02:52 UTC, merged