feat: [JIRA: HCPSDKFIORIUIKIT-2488] SwiftUI InformationView (ValidationView)
SAP/cloud-sdk-ios-fiori pull request #636
Opened 2024-02-13 21:16 UTC by xiaoqinggrace

2024-02-14 21:42 UTC, billzhou0223 requested changes

2024-02-14 21:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _InformationViewContentComponent {
I don't think we need a reusable component for the content of info view because the content is usually an existing styleable component and developers can use the corresponding style modifier to customize it.

2024-02-14 21:42 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _InformationViewComponent: _InformationViewContentComponent, _InformationViewIconComponent, _InformationViewTextComponent {}
Try this definition.

```
// sourcery: CompositeComponent
protocol _InformationViewComponent: _IconComponent, _DescriptionComponent {
    @ViewBuilder
    var content: () -> any View
}
```

2024-02-15 22:59 UTC, billzhou0223 requested changes

2024-02-15 22:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/InformationViewStyle.fiori.swift
> +                .descriptionStyle(.fiori)
This line is not necessary.

2024-02-15 22:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
> +    static func mediaImageStyle(_ style: some MediaImageStyle) -> CardMediaImageStyle {
Where did these changes come from? Your PR shouldn't affect other components that are not related to your feature.

I suspect this is caused by swiftformat or swiftlint. Try to run `setupForCollaborators.sh`, then run the sourcery script to regenerate the code to see if the issue is fixed.

2024-02-15 22:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/SupportingFiles/EnvironmentVariables.generated.swift
Same issue here.

2024-02-15 22:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/SupportingFiles/ResolvedStyle.generated.swift
Same issue.

2024-02-16 19:18 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/_generated/SupportingFiles/ComponentStyleProtocol+Extension.generated.swift
> +    static func mediaImageStyle(_ style: some MediaImageStyle) -> CardMediaImageStyle {
I did run the script but still found a lot of differences in the files generated. I will back out the changes not related to this feature.

2024-02-16 20:14 UTC, billzhou0223 reviewed
Changes looks good to me. Please fix the CI failure before merging.

2024-02-16 22:29 UTC, billzhou0223 approved these changes

2024-02-17 01:28 UTC, merged