feat: [HCPSDKFIORIUIKIT-2452] Illustrated Message
SAP/cloud-sdk-ios-fiori pull request #641
Opened 2024-02-21 17:59 UTC by JuliaSchnSAP

2024-03-01 18:02 UTC, billzhou0223 requested changes

2024-03-01 18:02 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +        IllustratedMessageHorizontalStyle()
I think the horizontal style should be a combination of layout and fiori style. You can rename `IllustratedMessageHorizontalStyle()` to `IllustratedMessageHorizontalLayoutStyle()`. Then return `IllustratedMessageHorizontalLayoutStyle().concat(.fiori)` here.

2024-03-01 19:10 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +            if size.width < 375 {
I think that `horizontalSizeClass` may not achieve the layout I am looking for because this view can be rendered at different sizes while using the same device size class

2024-03-02 01:25 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +        IllustratedMessageHorizontalStyle()
I followed those steps, but the expression IllustratedMessageHorizontalLayoutStyle().concat(.fiori) cannot get converted to the type IllustratedMessageStyle so I am getting a compiler error

2024-03-02 02:14 UTC, billzhou0223 requested changes

2024-03-02 02:14 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +            if size.width < 375 {
Please demonstrate. 

Where is this magic number 375 coming from? If it's from the spec, we need to ask designers to present such design relying on fixed width.

`horizontalSizeClass` only reflects window size and has nothing to do with device at all. It is recommended by Apple for creating adaptive design. Our components should only lay out its content based on the space given, not the actual device type.

2024-03-02 02:14 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +        IllustratedMessageHorizontalStyle()
Please demonstrate.

Where is this magic number 375 coming from? If it's from the spec, we need to ask designers to present such design relying on fixed width.

horizontalSizeClass only reflects window size and has nothing to do with device at all. It is recommended by Apple for creating adaptive design. Our components should only lay out its content based on the space given, not the actual device type.

2024-03-02 02:28 UTC, billzhou0223 requested changes

2024-03-02 02:28 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +        IllustratedMessageHorizontalStyle()
Because the type of the style is changed after concatenation. You need to figure out the correct type to specify in the where clause.

2024-03-02 03:21 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +            if size.width < 375 {
375 is from the spec, so I'll ask the designers if they can change it to use size classes

2024-03-04 17:30 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +            if size.width < 375 {
I wanted to add that this view can be displayed at different sizes for the same window size. It scales to take up the size allotted by its parent view. Would it still be appropriate to use `horizontalSizeClass`?

2024-03-04 22:12 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +            if size.width < 375 {
Actually we just changed the spec to only use left alignment so this is no longer a problem

2024-03-04 23:07 UTC, billzhou0223 requested changes

2024-03-04 23:07 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +        IllustratedMessageHorizontalStyle()
This problem is still unresolved. The layout style needs to be concatenated with fiori style in order to generate the correct result.

2024-03-06 18:32 UTC, billzhou0223 approved these changes

2024-03-06 18:32 UTC, merged