feat: 🎸 [HCPSDKFIORIUIKIT-2452] Add vertical layout style modifier to Illustrated Message
SAP/cloud-sdk-ios-fiori pull request #655
Opened 2024-03-08 18:58 UTC by JuliaSchnSAP

This component has a vertical layout by default. Adding a style modifier for this layout orientation would allow users to explicitly select either layout style instead of just the horizontal style. This would make the API more consistent

2024-03-11 21:22 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +/// Vertical layout style of the Illustrated Message. All content is displayed in one row. This is the default layout style
Do you actually mean one Column?

2024-03-11 21:23 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/IllustratedMessageStyle.fiori.swift
> +/// Vertical layout style of the Illustrated Message. All content is displayed in one row. This is the default layout style
is it actually one column?

2024-03-11 21:23 UTC, dyongxu requested changes
may update API doc

2024-03-12 18:57 UTC, billzhou0223 approved these changes

2024-03-12 18:57 UTC, merged