feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2460] SwiftUI NoteFormView
SAP/cloud-sdk-ios-fiori pull request #656
Opened 2024-03-09 00:43 UTC by janhuachu

SwiftUI Migration for NoteFormView and KeyValueFormView

Part of
✅ Closes:  HCPSDKFIORIUIKIT-2460

2024-03-11 17:48 UTC, billzhou0223 requested changes

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/InformationViewStyle.fiori.swift
> +    func informationView(icon: Image? = nil, description: AttributedString, isPresented: Binding<Bool>) -> some View {
Can we move `isPresented` parameter to the beginning of the list?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
> +                .padding(.top, 11)
Padding modifier can be moved into TitleStyle section.

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/KeyValueFormViewStyle.fiori.swift
> +                .padding(.bottom, 0)
same

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _TextViewComponent {
Name it `TextComponent`

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
> +                .padding(.top, 9)
Can we move it into fiori style definition?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
> +                .padding(.bottom, isInfoViewNeeded(configuration) ? 0 : 9)
Can we move it into fiori style definition?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/PlaceholderTextEditorStyle.fiori.swift
> +                .padding(.bottom, 0)
Can we move it into fiori style definition?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/PlaceholderTextEditorStyle.fiori.swift
> +                    .padding(.leading, 8)
Can we move it into fiori style definition?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/TextInputInfoViewStyle.fiori.swift
> +        .padding(.bottom, 11)
Can we move it into fiori style definition?

2024-03-11 17:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/TextInputInfoViewStyle.fiori.swift
> +    func textInputInfoView(isPresented: Binding<Bool>, icon: Image? = nil, description: AttributedString? = nil, counter: AttributedString? = nil) -> some View {
Move `isPresented` to the beginning of the parameter list.

2024-03-11 18:58 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _TextViewComponent {
This is for TextEditor which is equivalent to the UITextView which allows for user to do text input. Name it TextComponent may not imply this allows user input.

2024-03-11 19:04 UTC, billzhou0223 commented
Ok. Then keep it.

Best,
Bill


From: janhuachu ***@***.***>
Date: Monday, March 11, 2024 at 11:59 AM
To: SAP/cloud-sdk-ios-fiori ***@***.***>
Cc: Zhou, Bill ***@***.***>, Review requested ***@***.***>
Subject: Re: [SAP/cloud-sdk-ios-fiori] feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2460] SwiftUI NoteFormView (PR #656)

@janhuachu commented on this pull request.

________________________________

In Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift<https://github.com/SAP/cloud-sdk-ios-fiori/pull/656#discussion_r1520282621>:

> @@ -159,3 +159,15 @@ protocol _KpiCaptionComponent {

     // sourcery: @ViewBuilder

     var kpiCaption: AttributedString? { get }

 }

+

+// sourcery: BaseComponent

+protocol _PlaceholderComponent {

+    // sourcery: @ViewBuilder

+    var placeholder: AttributedString? { get }

+}

+

+// sourcery: BaseComponent

+protocol _TextViewComponent {

This is for TextEditor which is equivalent to the UITextView which allows for user to do text input. Name it TextComponent may not imply this allows user input.

—
Reply to this email directly, view it on GitHub<https://github.com/SAP/cloud-sdk-ios-fiori/pull/656#discussion_r1520282621>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACAFUFRJMSDKLSNT4XQPPOLYXYEJBAVCNFSM6AAAAABENURXNCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRYHA2TENBQG4>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-03-11 20:13 UTC, janhuachu commented on Sources/FioriSwiftUICore/_FioriStyles/NoteFormViewStyle.fiori.swift
> +                .padding(.top, 9)
Sure, except for .`focused($isFocused)`

2024-03-11 22:01 UTC, billzhou0223 approved these changes

2024-03-11 22:33 UTC, merged

2024-03-12 05:37 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/Action/Action.generated.swift
@janhuachu These changes shouldn't appear in the PR and shouldn't be checked in.

It could be due to your configuration of sourcery and swiftlint/swiftformat. Can you correct them? Try to run `setupCollaborator.sh` first.

2024-03-12 17:09 UTC, janhuachu commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/Action/Action.generated.swift
@billzhou0223 I did ran setupCollaborator.sh before I generated the file. I just ran it once and the results are the same that there are no changes to the checked in file.