feat: 🎸 styleable helper text and more action in toolbar
SAP/cloud-sdk-ios-fiori pull request #658
Opened 2024-03-11 07:24 UTC by xiaoyu0722

2024-03-14 19:31 UTC, billzhou0223 commented
@xiaoyu0722 These conflicts are caused by the recent code format changes after swiftformat version update. Please update your PR accordingly.

2024-03-14 19:44 UTC, dyongxu commented
@xiaoyu0722  There is some merge conflict. Need to resolve with latest main codeline.

2024-03-18 05:35 UTC, xiaoyu0722 commented
Hi @billzhou0223 @dyongxu  Conflicts resolved.

2024-03-18 17:00 UTC, dyongxu approved these changes

2024-03-18 18:38 UTC, billzhou0223 requested changes

2024-03-20 05:21 UTC, billzhou0223 approved these changes

2024-03-20 19:06 UTC, merged