feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2559] list style configurable
SAP/cloud-sdk-ios-fiori pull request #674
Opened 2024-03-28 02:59 UTC by xiaoyu0722

2024-03-28 19:49 UTC, billzhou0223 requested changes

2024-03-28 19:49 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct DestinationListStyleKey: EnvironmentKey {
Rename to `PickerListStyle`

2024-03-28 19:49 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +    func destinationStyle(_ style: any ListStyle) -> some View {
listPickerListStyle

2024-03-29 05:45 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +    func destinationStyle(_ style: any ListStyle) -> some View {
I tried to use the same name as its environment value, but can be compiled. I don't know why, just change a name, everything be good.
<img width="800" alt="Screenshot 2024-03-29 at 13 42 52" src="https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/b5baa320-ff8d-45bc-92a7-e04f665ceeb0">

2024-03-29 05:45 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct DestinationListStyleKey: EnvironmentKey {
Developer can set style for list picker directly, `ListPicker {}.listStyle(.grouped)`
Currently only destination view need to be styleable.

2024-03-29 20:00 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +    func destinationStyle(_ style: any ListStyle) -> some View {
Try to change the parameter type from `any ListStyle` to `some ListStyle`

2024-03-29 20:11 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct DestinationListStyleKey: EnvironmentKey {
I want to avoid using destination as a name of this API because it's a parameter name of navigation link and sdk users may not understand what it is used for if they don't know we are using navigation link internally. 

`ListPicker {}.listStyle(.grouped)` is not a valid use case since ListPicker itself is a just a view not a list. Setting listStyle won't have any affect on the destination list view, that 's why we need an additional API for it.

2024-04-02 00:27 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ListPickerItem+View.swift
> +struct DestinationListStyleKey: EnvironmentKey {
@billzhou0223 Or can we use `sublistStyle`?

2024-04-02 08:39 UTC, xiaoyu0722 commented
Still can not use same name, I use `listPickerListStyle` for public modifier and `listpickerListStyle` for internal environment value.

2024-04-02 20:49 UTC, billzhou0223 approved these changes

2024-04-02 20:49 UTC, merged