feat: 🎸 [JIRA:IOSSDKBUG-5] add variables to ChartLabelAttribute
SAP/cloud-sdk-ios-fiori pull request #692
Opened 2024-05-20 03:22 UTC by hengyi-zhang

add three variables(font, backgroundColor and styleAttributes) to ChartLabelAttributes, for User to custom chart label attributes conveniently

2024-05-20 18:34 UTC, billzhou0223 requested changes

2024-05-20 18:34 UTC, billzhou0223 commented on Sources/FioriCharts/Charts/Common/AxisTitle.swift
> +🌱 Running swiftformat 0.53.4...
Remove these redundant texts.

2024-05-20 18:34 UTC, billzhou0223 commented on Sources/FioriCharts/Charts/Common/XAxisView.swift
> +                                .font(axis.labels.font ?? .fiori(fixedSize: axis.labels.fontSize))
Do you need to set font here if the font attribute is already included in attributed string?

2024-05-20 18:34 UTC, billzhou0223 commented on Sources/FioriCharts/Charts/Common/AxisTitle.swift
> +    func attributedTitle(_ styleSheetAttributes: [NSAttributedString.Key: Any]) -> AttributedString {
What is `styleSheetAttributes`? We haven't added component-level stylesheet support in SwiftUI yet.

2024-05-20 18:34 UTC, billzhou0223 commented on Sources/FioriCharts/Model/ChartLabelAttributes.swift
> +    var mergedAttributes: [NSAttributedString.Key: Any] {
1. Why do we need to have both public style properties like `font`, `backgroundColor` and `styleAttributes`? These two types of API seem to have the same purpose so consider only keeping one of them. 
2. Do we want to reuse the same design in SAPFiori where we separate attributes from different sources (e.g. default, developer-set, stylesheet) in its own dictionary so that we can merge them in a certain order at rendering time?

@shengxu7 Your thoughts?

2024-05-20 18:39 UTC, shengxu7 commented on Sources/FioriCharts/Model/ChartLabelAttributes.swift
> +    var mergedAttributes: [NSAttributedString.Key: Any] {
Don't add styleAttributes at this moment.

2024-05-21 00:05 UTC, hengyi-zhang commented on Sources/FioriCharts/Charts/Common/AxisTitle.swift
> +🌱 Running swiftformat 0.53.4...
fixed!

2024-05-21 04:18 UTC, hengyi-zhang commented on Sources/FioriCharts/Charts/Common/XAxisView.swift
> +                                .font(axis.labels.font ?? .fiori(fixedSize: axis.labels.fontSize))
attributed string has been removed

2024-05-21 04:18 UTC, hengyi-zhang commented on Sources/FioriCharts/Model/ChartLabelAttributes.swift
> +    var mergedAttributes: [NSAttributedString.Key: Any] {
fixed!

2024-05-21 04:18 UTC, hengyi-zhang commented on Sources/FioriCharts/Charts/Common/AxisTitle.swift
> +    func attributedTitle(_ styleSheetAttributes: [NSAttributedString.Key: Any]) -> AttributedString {
fixed

2024-05-23 18:13 UTC, shengxu7 approved these changes

2024-05-23 18:13 UTC, shengxu7 approved these changes

2024-05-23 21:21 UTC, billzhou0223 approved these changes

2024-05-23 21:21 UTC, merged