feat: 🎸 [JIRA-HCPSDKFIORIUIKIT-2606] Form Cells: Mandator Field
SAP/cloud-sdk-ios-fiori pull request #701
Opened 2024-06-07 19:39 UTC by xiaoqinggrace

feat: [JIRA-HCPSDKFIORIUIKIT-2606] Form Cells: Mandatory Field Indicator

2024-06-08 00:18 UTC, dyongxu requested changes
Add a switch control

2024-06-08 00:18 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/SignatureView/SignatureCaptureViewExample.swift
> +                             .isRequired(true)
Add a switch control , similar to the other two test cases updated,  to turn on/off the "required indicator".

2024-06-10 16:51 UTC, billzhou0223 requested changes

2024-06-10 16:51 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +    }
We should make `isRequired` a environment value because it is a common property across all form views. So that you don't need to add it into each component individually.

2024-06-10 16:51 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +        }
This logic is very simple. If isRequired, append *. We don't need to handle else case.

2024-06-10 16:51 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _MandatoryIndicatorComponent {
I remember you said we don't want developers to customize the indicator so only exposing `isRequired` should be enough right?

2024-06-10 16:51 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var isRequired: Bool { get }
Make `isRequired` a environment value instead of adding it in every component.

2024-06-10 17:17 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +    }
Based on UX spec, the mandatory field is the feature for several form cells, not for all components.

2024-06-10 17:25 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +        }
There might be a use case in which the field is mandatory based on certain conditions such as the value of another field. I think it will be. more flexible by providing both if and else handling.

2024-06-10 17:44 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var isRequired: Bool { get }
Based on UX spec, the mandatory field is the feature for several form cells, not for all components.

2024-06-11 14:19 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +        }
Updated

2024-06-11 15:53 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +    }
The environment value defined in the base component model is not found in the generated API.

2024-06-12 20:13 UTC, billzhou0223 requested changes

2024-06-12 21:39 UTC, billzhou0223 approved these changes

2024-06-12 22:23 UTC, merged