chore: 🤖[HCPSDKFIORIUIKIT-2608] Clean up warnings : implicit conformance
SAP/cloud-sdk-ios-fiori pull request #711
Opened 2024-06-13 07:47 UTC by KevinZK

# Description

+ Stored property 'model' of 'Sendable'-conforming struct 'LinesShape' has non-sendable type 'ChartModel'

+ Stored property 'chartType' of 'Sendable'-conforming struct 'ColumnChartCategoryShape' has non-sendable type 'ChartType'

+ Stored property 'chartContext' of 'Sendable'-conforming struct 'PointsShape' has non-sendable type 'any ChartContext'

2024-06-13 21:01 UTC, billzhou0223 approved these changes

2024-06-13 23:10 UTC, dyongxu commented on Sources/FioriCharts/Model/ChartModel.swift
> +extension ChartModel: @unchecked Sendable {}
Not safe to use @unchecked 

e.g.  in ChartModel.swift , line 101
   @Published public var chartType: ChartType 
 Compiler will skip to check this line for "Sendable" conformance. However, since chartType is "var", it is not thread safe.

2024-06-13 23:10 UTC, dyongxu commented on Sources/FioriCharts/Charts/Common/ChartContext.swift
> +extension DefaultChartContext: @unchecked Sendable {}
Use of @unchecked is not safe.

2024-06-13 23:12 UTC, dyongxu requested changes
Remove the "@unchecked" change.
Leave the warning message there for now for these two files.
We may have to do some re-code for these two files to be thread safe.

2024-06-14 01:10 UTC, KevinZK commented
Due to thread safety issues, the warning is temporarily retained and PR is closed.

2024-06-14 01:10 UTC, closed without merging