chore: 🤖[HCPSDKFIORIUIKIT-2608] Clean up warnings: Logical problem
SAP/cloud-sdk-ios-fiori pull request #715
Opened 2024-06-13 08:39 UTC by KevinZK

# Description

+ Comparing non-optional value of type 'Bool' to 'nil' always returns true

2024-06-13 13:58 UTC, dyongxu approved these changes

2024-06-13 20:54 UTC, billzhou0223 requested changes

2024-06-13 20:54 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +            accString = labelString + (labelString.isEmpty ? ", " : "") + requiredText
Shouldn't the logic be `labelString.isEmpty ? "" : ", "`

2024-06-14 00:54 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/SignatureCaptureView+View.swift
> +            accString = labelString + (labelString.isEmpty ? ", " : "") + requiredText
fixed

2024-06-14 20:34 UTC, billzhou0223 approved these changes

2024-06-15 00:00 UTC, merged