fix: 🐛 ignore small diff for frame reader
SAP/cloud-sdk-ios-fiori pull request #729
Opened 2024-06-28 08:15 UTC by xiaoyu0722

2024-06-28 22:41 UTC, billzhou0223 requested changes

2024-06-28 22:41 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
May I ask why do you need to reply on `ContentFrameReaderPreferenceKey` rather than just calling `rect(frame)` in GeometryReader. 

You are not setting `lastFrame` anywhere.

2024-06-28 22:41 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct SizeReaderModifier: ViewModifier {
Same question here.

2024-07-01 03:17 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
Sorry, I missed the `self.lastFrame = newValue`
And the preference key is to get value changed constantly, and throw the value by the last closure.

2024-07-01 18:44 UTC, billzhou0223 requested changes

2024-07-01 18:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
Preference is useful for propagating value to its parent view. In your case, the sender and the receiver is the same view so there is no need to use preference I think.

```
func body(content: Content) -> some View {
        content
            .background(
                GeometryReader { geometry in
                    let frame = geometry.frame(in: self.coordinateSpace)
                    if abs(frame.width - self.lastFrame.width) > 0.001 ||
                                abs(frame.height - self.lastFrame.height) > 0.001 ||
                                abs(frame.origin.x - self.lastFrame.origin.x) > 0.001 ||
                                abs(frame.origin.y - self.lastFrame.origin.y) > 0.001
                            {
                                self.lastFrame = frame
                                self.rect(newValue)
                            }

                    Color.clear
                }
            )
    }
```

2024-07-02 01:05 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
Can not call `rect(newValue)` directly in geometry reader.

2024-07-09 22:21 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
Why?

2024-07-11 18:22 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +struct FrameReaderModifier: ViewModifier {
What's the error you see if you call it in GeometryReader?

2024-07-22 03:22 UTC, xiaoyu0722 commented
I will close this PR and no need to update this.

2024-07-22 03:22 UTC, closed without merging