feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-1940] profile header
SAP/cloud-sdk-ios-fiori pull request #731
Opened 2024-07-01 07:19 UTC by xiaoyu0722

|static|animatable|
|-|-|
|![Simulator Screenshot - iPad Pro 13-inch (M4) (16GB) - 2024-07-01 at 15 04 04](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/b729791d-c584-4763-b6d9-97f42845154f)|![Simulator Screenshot - iPad Pro 13-inch (M4) (16GB) - 2024-07-01 at 15 04 09](https://github.com/SAP/cloud-sdk-ios-fiori/assets/2142582/1edd2af8-89ee-41ab-905e-9c201e6c6cbb)|

2024-07-01 19:13 UTC, billzhou0223 requested changes

2024-07-01 19:13 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/ProfileHeader/ProfileHeaderAnimatableExample.swift
> +                })
This should be handled by SDK if possible.

2024-07-01 22:20 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/ProfileHeaderStyle.fiori.swift
> +public struct ProfileHeaderBaseStyle: ProfileHeaderStyle {
1. Add support for "right to left" layout
2. Add accessibility support for the component

2024-07-01 22:21 UTC, dyongxu requested changes
"right to left" layout to be supported
accessibility voice over support to be added

2024-07-02 06:47 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var transitionProgress: CGFloat { get }
Like [swiftui-introspect](https://github.com/siteline/swiftui-introspect) to get the offset of its superview to calculate the progress?

2024-07-02 08:17 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_FioriStyles/ProfileHeaderStyle.fiori.swift
> +public struct ProfileHeaderBaseStyle: ProfileHeaderStyle {
RTL is supported, and accessibility is also enabled by default.

2024-07-03 23:28 UTC, dyongxu approved these changes

2024-07-05 03:59 UTC, dyongxu commented
@xiaoyu0722 Looks like some other PR has checked in some generated files, causing your merge conflict. Need to pull latest  main to resolve conflict.

2024-07-09 07:01 UTC, xiaoyu0722 commented
Hi @billzhou0223 , need review again.

2024-07-09 22:32 UTC, billzhou0223 approved these changes

2024-07-10 08:36 UTC, merged