feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-1933]SwiftUI Timeline
SAP/cloud-sdk-ios-fiori pull request #734
Opened 2024-07-03 09:10 UTC by zzchao-1999

2024-07-03 16:56 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .font(.fiori(forTextStyle: .headline))
```suggestion
                .font(.fiori(forTextStyle: .headline), weight: .semibold)
```
I think UIKit uses semibold.

2024-07-03 16:57 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .foregroundColor(self.isEnabled ? Color.preferredColor(.primaryLabel) : Color.preferredColor(.separator))
```suggestion
                .foregroundColor(self.isEnabled ? Color.preferredColor(.primaryLabel) : Color.preferredColor(.quaternaryLabel))
```
I think UIKit uses quaternaryLabel when disabled.

2024-07-03 21:34 UTC, dyongxu commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +public struct TimelineNodesView: View {
```suggestion
public struct TimelineNodeView: View {
```
This view represents one single node. Not multiple nodes. So, it should be singular form, not plural.

2024-07-03 21:34 UTC, dyongxu commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +/// 'TImelineNodesView' displays an image representing a timeline node.
```suggestion
/// 'TimelineNodeView' displays an image representing a timeline node.
```

2024-07-03 21:35 UTC, dyongxu commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +    /// timeline event inprogress
```suggestion
    /// timeline event in progress
```

2024-07-03 21:50 UTC, dyongxu commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +public enum TimelineNodeType {
TimelineNodeStatus and TimelineNodeType look like pretty much same, except for "custom" type.
Is it doable to merge these two enums into one enum (TimelineNodeType)?  Similar to UIKit: cell.nodeType.

2024-07-03 22:08 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    /// check if show upper vertical line
```suggestion
    /// Show upper vertical line or not. Default is to show.
```

2024-07-03 22:16 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// SwiftUI all list styles include separators by default. Because of this default setting, there can be a divider line or a separator in between each item on the timelineMarker in the list. This is
```suggestion
/// All list styles in SwiftUI include separators by default. This is why there is a divider line or a separator between each item for the timelineMarker in the list. To get rid of the separator, set ‘listRowSeparator’ modifier to hide.
```

2024-07-03 22:22 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// SwiftUI all list styles include separators by default. Because of this default setting, there can be a divider line or a separator in between each item on the timeline in the list. This is not an
```suggestion
/// All list styles in SwiftUI include separators by default. That is why there is a divider line or a separator between two timelines in the list. To get rid of the separator, set ‘listRowSeparator’ modifier to be hidden.
```

2024-07-03 22:25 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// `TimelineNowIndicator` designed to present now indicator in a Timeline view.
```suggestion
/// `TimelineNowIndicator` is used to present now indicator in a Timeline view.
```

2024-07-03 22:27 UTC, dyongxu requested changes
comments inlined

2024-07-05 07:55 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .font(.fiori(forTextStyle: .headline))
I double checked UIkit code, I didn't find weight property  in headline font style.

2024-07-05 07:56 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .foregroundColor(self.isEnabled ? Color.preferredColor(.primaryLabel) : Color.preferredColor(.separator))
Updated all disabled text color to quaternaryLabel.

2024-07-05 07:56 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +public struct TimelineNodesView: View {
Updated it.

2024-07-05 07:56 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +/// 'TImelineNodesView' displays an image representing a timeline node.
Updated it.

2024-07-05 07:57 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +    /// timeline event inprogress
Updated it.

2024-07-05 07:59 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// `TimelineNowIndicator` designed to present now indicator in a Timeline view.
Updated it.

2024-07-05 07:59 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// SwiftUI all list styles include separators by default. Because of this default setting, there can be a divider line or a separator in between each item on the timeline in the list. This is not an
Updated it.

2024-07-05 08:00 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodesView.swift
> +public enum TimelineNodeType {
Refactored the code, pls review it again, thanks!

2024-07-05 08:00 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    /// check if show upper vertical line
Updated it.

2024-07-05 08:00 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// SwiftUI all list styles include separators by default. Because of this default setting, there can be a divider line or a separator in between each item on the timelineMarker in the list. This is
Updated it.

2024-07-08 20:47 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .font(.fiori(forTextStyle: .headline))
It is in UIKit TimelineCell.swift, line 1099:
     self.headlineLabel.font = UIFont.preferredFioriFont(forTextStyle: .headline, weight: .semibold)

2024-07-09 23:33 UTC, billzhou0223 requested changes
Please attach a screenshot for each timeline component

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +}
```
protocol _SecondaryTimestampComponent {
    // sourcery: @ViewBuilder
    var secondaryTimestamp: TextOrIcon? { get }
}
```

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _NodeImageComponent {
Rename to `_TimelineNodeComponent`

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +}
Do we really need to make these lines as reusable components? It doesn't make sense to allow developers to pass any view for the line. Let's remove them and draw the lines internally in SDK.

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _TrailingHorizontalLineComponent {
see the above comment

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineTimeStackComponent: _TimestampLabelComponent, _SecondaryTimestampLabelComponent, _SecondaryTimestampImageComponent {}
No need to define a stack component like this. You can just create a VStack to group those views in the makeBody of the base style.

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineMarkerMainStackComponent: _TitleComponent {}
See the above comment.

2024-07-09 23:33 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineMainStackComponent: _TitleComponent, _SubtitleComponent, _AttributeComponent, _StatusComponent, _SubstatusComponent, _SubAttributeComponent {}
See the above comment.

2024-07-11 03:35 UTC, dyongxu approved these changes

2024-07-11 03:35 UTC, dyongxu commented
@zzchao-1999 There is a merge conflict here.

2024-07-15 07:22 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodeView.swift
> +public struct TimelineNodeView: View {
Since we have defined component _TimelineNodeComponent, there will be conflict error if rename it TimelineNode.

2024-07-15 07:22 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/Views/TimelineNodeView.swift
> +public enum TimelineNodeType {
Updated it, pls help review again, thanks!

2024-07-15 07:22 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _TimestampLabelComponent {
Updated it.

2024-07-15 07:23 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +}
Updated it.

2024-07-15 07:23 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _NodeImageComponent {
Updated it.

2024-07-15 07:23 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +}
Removed them.

2024-07-15 07:23 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _TrailingHorizontalLineComponent {
Removed it.

2024-07-15 07:24 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineTimeStackComponent: _TimestampLabelComponent, _SecondaryTimestampLabelComponent, _SecondaryTimestampImageComponent {}
Updated it.

2024-07-15 07:24 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineMarkerMainStackComponent: _TitleComponent {}
Updated it.

2024-07-15 07:24 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +protocol _TimelineMainStackComponent: _TitleComponent, _SubtitleComponent, _AttributeComponent, _StatusComponent, _SubstatusComponent, _SubAttributeComponent {}
Updated it.

2024-07-15 07:39 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/TimelineStyle.fiori.swift
> +                .font(.fiori(forTextStyle: .headline))
Updated it, thanks!

2024-07-16 19:18 UTC, billzhou0223 requested changes

2024-07-16 19:18 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _SecondaryTimestampComponent {
You need to specify the backing component of `TextOrIcon`. 

Example:
```
// sourcery: BaseComponent
protocol _StatusComponent {
    // sourcery: resultBuilder.name = @ViewBuilder, resultBuilder.backingComponent = TextOrIconView
    var status: TextOrIcon? { get }
}
```

2024-07-17 02:35 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _SecondaryTimestampComponent {
Added backing component, pls review it again, thanks!

2024-07-17 22:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _SecondaryTimestampComponent {
Did you rerun the script after you modified this protocol?

2024-07-17 22:53 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +protocol _SecondaryTimestampComponent {
I just realized `// sourcery: @ViewBuilder` will also work...

2024-07-17 22:53 UTC, billzhou0223 approved these changes

2024-07-18 00:33 UTC, merged