feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2631] RatingControlFormView SwiftUI implementation
SAP/cloud-sdk-ios-fiori pull request #735
Opened 2024-07-08 18:55 UTC by janhuachu

[JIRA:HCPSDKFIORIUIKIT-2631] RatingControlFormView SwiftUI implementation

✅ Closes: JIRA:HCPSDKFIORIUIKIT-2631

2024-07-09 06:18 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +            if !configuration.subtitle.isEmpty {
Nor sure what the logic is based on or what the requirements are. However, we might consider displaying the subtitle, when it is not empty, either in one column or alongside the Title and RatingControl in one row. Then, the subtitle could be utilized as the value label, as described in JIRA [FIORIDESIGN-11992](https://jira.tools.sap/browse/FIORIDESIGN-11992). Consequently, we wouldn't need to add another 'Text' element for the value label. What do you think about this approach? If you agree, you can go ahead and make the changes, or I can modify it later.

2024-07-09 16:35 UTC, billzhou0223 requested changes

2024-07-09 16:35 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var isStacked: Bool { get }
Please name it `var axes: Axis`. (See `ScrollView`)

2024-07-09 16:35 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +                }
Title style and subtitle style should go into their corresponding style definition.

2024-07-09 17:55 UTC, janhuachu commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +            if !configuration.subtitle.isEmpty {
I think the subtitle is something that the developer to put for describing the rating is for.
It is different than what [FIORIDESIGN-11992](https://jira.tools.sap/browse/FIORIDESIGN-11992) is trying to add, which is a value description. I think we should not reuse the subtitle field.

2024-07-09 18:48 UTC, janhuachu commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +                }
OK

2024-07-09 18:48 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var isStacked: Bool { get }
OK

2024-07-09 18:49 UTC, janhuachu commented
@billzhou0223 Updated per your comments. Please review again.

2024-07-09 22:16 UTC, billzhou0223 approved these changes

2024-07-10 01:37 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +            if !configuration.subtitle.isEmpty {
OK. In that case, we don't consider to reuse it.

2024-07-10 01:40 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlFormViewStyle.fiori.swift
> +            if !configuration.subtitle.isEmpty {
OK. In that case, we don't consider to reuse it.

2024-07-10 01:40 UTC, JunSong-SH approved these changes

2024-07-10 09:49 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/RatingControlFormView/RatingControlFormView.generated.swift
> +    @Binding var rating: Int
BTY, not sure if you can change the rating to float as we need support half star later. Also, in RatingControl. We might need App team to pass in rating value like 2.1, 3.7 etc,. I ask this since I am not sure if I can finish the later change to support half star in 24.8. If not, we need change the API in 24.12.

2024-07-10 17:18 UTC, merged