fix: 🐛 [JIRA: FIORIDESIGN-12263] fix UI review issues
SAP/cloud-sdk-ios-fiori pull request #752
Opened 2024-07-24 09:32 UTC by zzchao-1999

Fixed below issues:
  Addressed Stepper UI review issues;
  Added importStatement type in Sourcery template;
  Disabled decrement/increment action when textfield is focused.

2024-07-24 23:13 UTC, dyongxu requested changes
Add some some comments how the number 768 is based on. So it will be easier for future maintenance

2024-07-24 23:13 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
> +            let padding: CGFloat = self.horizontalSizeClass == .compact ? 16 : (self.horizontalSizeClass == .regular ? (UIScreen.main.bounds.width > 768 ? 48 : 24) : 16)
Where is this "768" based on ?  Is this from Design Spec?

2024-07-25 00:17 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
> +            let padding: CGFloat = self.horizontalSizeClass == .compact ? 16 : (self.horizontalSizeClass == .regular ? (UIScreen.main.bounds.width > 768 ? 48 : 24) : 16)
UI designer mentioned it in the comments.
https://www.figma.com/design/nEQ7KySGouQuzJHnM4Tagi/Stepper-Form-Cell?node-id=3096-4503&t=SxhVjTTWtydn5RSD-0
And iOS design guidelines described it.
https://experience.sap.com/fiori-design-ios/article/adaptive-design/#fullwidth-regular

2024-07-25 01:15 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
> +            let padding: CGFloat = self.horizontalSizeClass == .compact ? 16 : (self.horizontalSizeClass == .regular ? (UIScreen.main.bounds.width > 768 ? 48 : 24) : 16)
And added comments for padding information.

2024-07-25 16:50 UTC, dyongxu approved these changes

2024-07-25 19:12 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
> +                    .allowsHitTesting(self.isEnabled && !self.isFocused)
Why do you need to add `.allowHitTesting` in addition to `.disabled`?

2024-07-26 03:27 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_FioriStyles/StepperViewStyle.fiori.swift
> +                    .allowsHitTesting(self.isEnabled && !self.isFocused)
The increment/decrement buttons had an onSimultaneousTapGesture attached, but their disabled state did not prevent gesture recognition, so we use allowHitTesting to prevent actions.

2024-07-29 22:55 UTC, billzhou0223 approved these changes

2024-07-29 22:55 UTC, merged