feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2686] Button update
SAP/cloud-sdk-ios-fiori pull request #753
Opened 2024-07-30 02:36 UTC by hengyi-zhang

2024-08-01 22:51 UTC, billzhou0223 requested changes

2024-08-01 22:51 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +    init(isSelectionPersistent: Bool = false,
Let's extend existing init to support image display.

```
public init(isSelectionPersistent: Bool = false,
                action: ((UIControl.State) -> Void)? = nil,
                @ViewBuilder label: @escaping (UIControl.State) -> any View，
                @ViewBuilder image: @escaping (UIControl.State) -> any View = { _ in },
                imagePosition: Position = .left,
                spacing: CGFloat = 8)
```
You need to update other init accordingly as well. `FioriButtonStyleConfiguration` needs to be updated as well.

We need to provide default UI based on loading state. We can add a new style to achieve that.

```
FioriButton()
    .fioriButtonStyle(FioriLoadingButtonStyle(state: .inProgress // or .success))
```

2024-08-09 08:26 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/FioriButton/FioriButton.swift
> +    init(isSelectionPersistent: Bool = false,
Fixed!

2024-08-13 19:24 UTC, billzhou0223 approved these changes
LGTM!

2024-08-13 20:10 UTC, merged