fix: IOSSDKBUG-282 - JMC welcome screen legal disclaimer bg color
SAP/cloud-sdk-ios-fiori pull request #757
Opened 2024-08-01 19:02 UTC by CharlesXu0488

Adding default JMC welcome screen background color so that the legal disclaimer's background color matches conversation scroll view's background color.

After adding background color
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/04f9a3be-c074-49d8-8275-cd8a5c549fc3">

Before adding background color
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/5be59463-9851-4033-a2da-1964fab7aed6">

2024-08-01 22:21 UTC, dyongxu approved these changes

2024-08-01 22:52 UTC, billzhou0223 approved these changes

2024-08-01 22:54 UTC, billzhou0223 requested changes

2024-08-01 22:54 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/JouleWelcomeScreenStyle.fiori.swift
> +        .background(Color.preferredColor(.primaryBackground))
You should add the background in the `JouleWelcomeScreenFioriStyle.ContentFioriStyle`. The base style is only for layout purpose. Styling attributes should be set in corresponding fiori style.

2024-08-01 23:09 UTC, CharlesXu0488 commented on Sources/FioriSwiftUICore/_FioriStyles/JouleWelcomeScreenStyle.fiori.swift
> +        .background(Color.preferredColor(.primaryBackground))
OK, done.

2024-08-02 05:04 UTC, billzhou0223 approved these changes

2024-08-02 14:27 UTC, dyongxu approved these changes

2024-08-02 18:16 UTC, merged