feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2708] avatars enhancement
SAP/cloud-sdk-ios-fiori pull request #773
Opened 2024-08-14 08:55 UTC by xiaoyu0722

<img src="https://github.com/user-attachments/assets/94fe5fae-16de-40a2-aca8-e6b732a926c9" width="40%">

2024-08-15 00:03 UTC, dyongxu requested changes
comment inlined

2024-08-15 00:15 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +// sourcery: add_env_props = "footnoteIconsTextPosition"
Agreed. New features only need to be added to new object item.

2024-08-15 00:20 UTC, billzhou0223 requested changes

2024-08-15 00:20 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
> +    func footnoteIconsText(@ViewBuilder text: () -> any View) -> some View {
why is `footnoteIconsText` a modifier instead of a parameter passed from init similar to `footnoteIcons`?

2024-08-15 06:42 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +// sourcery: add_env_props = "footnoteIconsTextPosition"
It's still used as backing component for `_FootnoteIconsComponent`.

2024-08-15 06:52 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
> +    func footnoteIconsText(@ViewBuilder text: () -> any View) -> some View {
`_FootnoteIconsComponent` is a base component, seems it's not supported to add another `text` in this protocol by styleable template.
Also it also makes no sense if add it to `ObjectItem`. It should be grouped with footnote icons or avatars.
And I can't find a good way to support an array of indexed views styling.

2024-08-15 19:47 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
> +    func footnoteIconsText(@ViewBuilder text: () -> any View) -> some View {
Can you treat `FootnoteIconsText` as a new base component.

And add a new protocol (neither base or composite component) to group them. 

```
// sourcery: BaseComponent
protocol _FootnoteIconsTextComponent {
    var footnoteIconsText: AttributedString? { get }
}

protocol _FootnoteAvatarComponent: _FootnoteIconsComponent, _FootnoteIconsTextComponent {
    var footnoteIconsTextPosition: Position { get } 
}

// sourcery: CompositeComponent
protocol _ObjectItemComponent: _FootnoteAvatarComponent {}
```

2024-08-16 05:31 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
> +    func footnoteIconsText(@ViewBuilder text: () -> any View) -> some View {
So you want to init the text by `ObjectItem`?
```swift
init(@ViewBuilder title: () -> any View,
...
     @AvatarsBuilder avatars: () -> any View = { EmptyView() },
     @FootnoteIconsBuilder footnoteIcons: () -> any View = { EmptyView() },
     @ViewBuilder footnoteIconsText: () -> any View = { EmptyView() }
...
```

2024-08-16 17:27 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/CustomBuilder/FootnoteIconsBuilder.swift
> +    func footnoteIconsText(@ViewBuilder text: () -> any View) -> some View {
Correct. `footnoteIconsText` is just a new data field so we should handle it the same way as `footnoteIcons`.

2024-08-20 17:33 UTC, dyongxu approved these changes

2024-08-22 19:39 UTC, billzhou0223 approved these changes

2024-08-22 19:39 UTC, merged