feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-1934]SwiftUI TimelinePreviewView
SAP/cloud-sdk-ios-fiori pull request #780
Opened 2024-08-19 17:21 UTC by zzchao-1999

<img width="350" alt="Screenshot 2024-08-20 at 00 58 45" src="https://github.com/user-attachments/assets/38d39942-bf6e-4e4c-bab2-06440d6109f5">

2024-08-21 03:10 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +            TimelinePreview(headerTitle: { Text("Timeline") }, data: self.$items0)
In UIKit, headerTitle can be set to be hidden or shown, e.g.
cell.timelinePreviewView.header.isHidden = false

Can we make this "headerTitle" to be optional (or use other way), and have another test case for this , to achieve the same effect as UIKit ?

2024-08-21 03:14 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/TimelinePreviewStyle.fiori.swift
> +        let itemCount: Int = self.horizontalSizeClass == .compact ? 2 : (self.horizontalSizeClass == .regular ? (UIScreen.main.bounds.width > 768 ? 4 : 3) : 3)
Not to use UIScreen. Otherwise, it will fail to compile on visionOS

2024-08-21 03:24 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +        TimelinePreviewItemModel(title: "LooooooooooooooooooooooongTitle", timelineNode: TimelineNodeType.start, due: ISO8601DateFormatter().date(from: "2024-07-23T12:00:00Z")!, dateFormat: "EEEE, MM
This is a case I think not covered in UIKit.  The dateFormatter in UIKit is applied to the whole FUITimelinePreview, so, each node will have the same formatter. And the length of the datetime will be the same.
In SwiftUI, it is ok to allow each node to have its own dateFormatter. But we will need to make the alignment correct(each node's datetime to be topleft aligned. )

2024-08-21 03:25 UTC, dyongxu requested changes
comments inlined . Also, check/test if right to left language is supported.

2024-08-21 22:03 UTC, billzhou0223 requested changes

2024-08-21 22:03 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
The model should have its own init for building the timeline preview item. 

```
public init(@ViewBuilder title: () -> any View,
                @ViewBuilder icon: () -> any View = { EmptyView() },
                @ViewBuilder timelineNode: () -> any View,
                @ViewBuilder timestamp: () -> any View = { EmptyView() })

public init(model: TimelinePreviewItemModel)
```

2024-08-22 14:37 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +            TimelinePreview(headerTitle: { Text("Timeline") }, data: self.$items0)
Added a new parameter "showHeader" to show header or not.

2024-08-22 14:39 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +        TimelinePreviewItemModel(title: "LooooooooooooooooooooooongTitle", timelineNode: TimelineNodeType.start, due: ISO8601DateFormatter().date(from: "2024-07-23T12:00:00Z")!, dateFormat: "EEEE, MM
Yes, datetime aligns topleft with lastTextBaseline.

2024-08-22 14:40 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +}
Removed _SeeAllActionComponent and _HeaderTitleComponent, updated them to _TitleComponent and _ActionComponent.

2024-08-22 15:01 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
In TimelinePreviewItem, I defined the parameter 'data' as TimelinePreviewItemModel type. This is optional, but it can simplify the process of passing data into the TimelinePreviewItem. For example, determine the appropriate node image size based on the node type.
    /// the data of timeline preview item
    var data: TimelinePreviewItemModel { get }

2024-08-22 20:02 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +            TimelinePreview(headerTitle: { Text("Timeline") }, data: self.$items0)
How about creating a new reusable base component `_OptionalTitleComponent` for this purpose.

2024-08-22 20:09 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
When developers init the component with model, they want to quickly show the data without having to configuring the view. SDK needs to setup the view and styles based on the data passed in. Please keep these two types of init separate.

2024-08-23 13:55 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
Removed model from timelinePreviewItem.

2024-08-23 14:02 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +            TimelinePreview(headerTitle: { Text("Timeline") }, data: self.$items0)
The header includes two controls: a title (optional) and a 'see all' action(optional). If the title and see all action both are omitted, an 'ambiguous use of init(optionTitle, action, data)' error occurs.

  public init(@ViewBuilder optionalTitle: () -> any View = { EmptyView() },
              @ViewBuilder action: () -> any View = { EmptyView() },
              data: Binding<[TimelinePreviewItemModel]>)
  {
      self.optionalTitle = OptionalTitle { optionalTitle() }
      self.action = Action { action() }
      self._data = data
  }

public extension TimelinePreview {
    init(optionalTitle: AttributedString? = nil,
         action: FioriButton? = nil,
         data: Binding<[TimelinePreviewItemModel]>)
    {
        self.init(optionalTitle: { OptionalText(optionalTitle) }, action: { action }, data: data)
    }
}

2024-08-23 16:08 UTC, dyongxu approved these changes

2024-08-23 16:09 UTC, dyongxu commented
@zzchao-1999 Need to resolve merge conflict with the latest main branch.

2024-08-27 07:36 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/Timeline/TimelinePreviewExample.swift
> +            TimelinePreview(headerTitle: { Text("Timeline") }, data: self.$items0)
Added a new base component: _OptionalTitleComponent, show the header when title or action isn't empty, otherwise hide the header.

2024-08-27 19:50 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
We can define `TimelinePreviewItemModel` as a protocol. Both `TimelinePreviewItem` and `TimelinePreview` can use it for initialization.

```
public protocol TimelinePreviewItemModel {}

TimelinePreview(..., items: [TimelinePreviewItemModel])

TimelinePreviewItem(model: TimelinePreviewItemModel)
```

2024-09-03 01:15 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_generated/StyleableComponents/TimelinePreviewItem/TimelinePreviewItem.generated.swift
> +    public init(@ViewBuilder title: () -> any View,
Added protocol: TimelinePreviewItemModel and updated code accordingly.

2024-09-04 19:39 UTC, billzhou0223 approved these changes

2024-09-04 23:57 UTC, merged