feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2716]Step Progress Indicator Enhancement
SAP/cloud-sdk-ios-fiori pull request #784
Opened 2024-08-28 09:50 UTC by KevinZK

* Add image support for the Step Progress Indicator Component

![Simulator Screenshot - iPhone 15 Pro - 2024-08-28 at 17 49 50](https://github.com/user-attachments/assets/89721133-570e-487f-841d-61b735a4072f)

2024-08-28 20:10 UTC, billzhou0223 requested changes

2024-08-28 20:10 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
> +                    if self.stepItem.icon.isEmpty {
Have you tested this code? I suspect that `Image.isEmpty` won't return the correct value.

2024-08-29 01:27 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
> +                    if self.stepItem.icon.isEmpty {
The `isEmpty` extension was newly added by you on February 2, and the result of my test is valid.

Implementation
```
public protocol _ViewEmptyChecking {
    // Check if the view is an empty view. Some SDK components implement this protocol to define their own empty logic.
    var isEmpty: Bool { get }
}
extension View {
    var isEmpty: Bool {
        if self is EmptyView {
            return true
        }
        
        if let self = self as? _ViewEmptyChecking {
            return self.isEmpty
        }
        
        return false
    }
}
extension Optional: _ViewEmptyChecking where Wrapped: View {
    public var isEmpty: Bool {
        if case .none = self {
            return true
        }
        
        if case .some(let wrapped) = self {
            return wrapped.isEmpty
        }
        
        return false
    }
}
```

2024-08-29 23:02 UTC, billzhou0223 approved these changes

2024-08-30 07:18 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
> +                    }
`Icon steps and numeric steps cannot be used together.`
Icons and number text may mix together by this logic. Please double check with designer.

2024-08-30 23:39 UTC, merged