feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2716]Step Progress Indicator
SAP/cloud-sdk-ios-fiori pull request #787
Opened 2024-09-02 03:14 UTC by KevinZK

*Add stepProgressIndicatorNodeType for step node.

## Description
Add `StepProgressIndicatorNodeType` for stepProgressIndicator to set the nodetype style.

 + mixture: Allow nodes to display numeric step and icon step in a mixture.
 + icon: Only allow the display of icon step.
 + text：Only allow the display of numeric step.

## Usage
```
StepProgressIndicator(selection: self.$selection,
                                  stepItems: self.steps).stepProgressIndicatorNodeType(.icon)

```

2024-09-03 18:09 UTC, dyongxu commented
@xiaoyu0722 Can you review this enhancement as well ?

2024-09-04 19:50 UTC, billzhou0223 requested changes

2024-09-04 19:50 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +public enum StepProgressIndicatorNodeType {
There is already a type for this purpose called `TextOrIcon`. The node should be declared as this type so that developers can pass either text or icon as needed.

2024-09-05 09:00 UTC, xiaoyu0722 requested changes

2024-09-05 09:00 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
If this is not supported, why public it?
Can we handle this by a default empty icon(like dashed box in Figma) or just ignore icons and use index directly by data checking?  Add a statement in doc that how we handle the mixed data.

2024-09-06 01:07 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
Only an option is provided, allowing developers to decide for themselves. The placeholder icon 'app.dashed' has been provided.

2024-09-06 23:18 UTC, billzhou0223 requested changes

2024-09-06 23:18 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
This is a breaking change. Use available tag in such case.

2024-09-06 23:18 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
You don't need this type after adopting `TextOrIcon`.

2024-09-09 01:14 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
`var icon: Image? { get } `was added in the previous PR and should not be a breaking change.

2024-09-09 02:34 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
Sorry, I don't understand why. 

My thinking is like this.
`TextOrIcon` is only applicable to Node. The enumeration `StepProgressIndicatorNodeType` is the display form of all nodes in the StepProgressIndicator component.

Anyway, my latest commit has removed `mixture`.

2024-09-09 19:37 UTC, billzhou0223 requested changes

2024-09-09 19:37 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
I mean we can remove this enum type `StepProgressIndicatorNodeType` not just one of the cases. In the old implementation made by @xiaoyu0722, if the icon is nil we show text by default. Otherwise we use the custom icon from user. I'd like to keep this behavior. 

Where did you get this requirement of allowing switching between text and icon for the default node? If it's not something on the spec, don't change it.

2024-09-09 19:44 UTC, billzhou0223 requested changes

2024-09-09 19:44 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
A breaking change means you changed or removed a public api that was already released... It will break the app code that relies on it. We need to use available keyword for such changes.

BTW, do not mark a problem as resolved if you are not sure what you did is correct or not. Otherwise I might miss these issues in the next review.

2024-09-10 00:15 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
Designer's requirements“Icon steps and numeric steps cannot be used together”

2024-09-10 00:22 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
I mean that this PR and #784 are actually both modifications to the Step Progress Indicator. The modification of var icon: Image? { get } is newly added in #784.
Is it still necessary to continue marking "available" in this situation?

2024-09-10 00:48 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    case mixture
That's more like a guideline to app developers. We don't want to add this restriction to this component.

2024-09-10 00:49 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
No if you recently added it and hasn't been released

2024-09-10 01:06 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/StepItem.swift
> +    var node: TextOrIcon? { get }
Got it

2024-09-10 23:24 UTC, billzhou0223 requested changes

2024-09-10 23:24 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
> +                    if self.stepItem.node != nil {
You can use `TextOrIconView` here.

2024-09-11 02:45 UTC, KevinZK commented on Sources/FioriSwiftUICore/Views/StepProgressIndicator/_DefaultSteps.swift
> +                    if self.stepItem.node != nil {
`TextOrIconView` makes code more concise.

2024-09-11 03:17 UTC, KevinZK commented
CI Error：

The actions/download-artifact in CI.yml is version v1.
Is it updated to actions/download-artifact@v2?

2024-09-11 18:34 UTC, billzhou0223 approved these changes

2024-09-11 18:40 UTC, billzhou0223 commented
> CI Error：
> 
> The actions/download-artifact in CI.yml is version v1. Is it updated to actions/download-artifact

Version was taken care of by #799

2024-09-13 01:28 UTC, xiaoyu0722 approved these changes

2024-09-13 01:42 UTC, merged