feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2708] avatar stack support
SAP/cloud-sdk-ios-fiori pull request #788
Opened 2024-09-03 09:06 UTC by xiaoyu0722

|grouped|horizontal|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-03 at 17 04 52](https://github.com/user-attachments/assets/c29dd0ef-fcd9-4ce1-9c20-e229101994ad)|![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-03 at 17 05 00](https://github.com/user-attachments/assets/413cb1ae-8965-4c05-bc9b-efa3c4d1ff17)|

2024-09-04 20:12 UTC, billzhou0223 requested changes

2024-09-04 20:12 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/AvatarStack/AvatarStackExample.swift
> +        .avatarSize(self.avatarSize)
Environment is useful when you have multiple UI elements of the same type in the hierarchy and you want to be able to set something in the parent and propagate down to all the children. In your case, I don't see this type of requirement.

Let's try to make some of the properties as init params. The others can be configured through style modifier.

```
AvatarStack(layout: .grouped, spacing: 8, ...)
      .avatarsStyle {
             Avatars($0)
                  .borderColor()
                  .borderWidth()
      }
```

2024-09-05 06:43 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/AvatarStack/AvatarStackExample.swift
> +        .avatarSize(self.avatarSize)
These environments are for uniform settings of avatars.
`.avatarsStyle {}` is for the whole `avatars` which is new grouped view generated by `AvatarBuilder`.

If developer want to set different styles for different avatars, they should do the styles setting in the avatars initialization like below way.

<img width="1235" alt="Screenshot 2024-09-05 at 14 39 45" src="https://github.com/user-attachments/assets/d95b65b7-0368-4217-8d28-8107f7917861">

2024-09-06 23:11 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/AvatarStack/AvatarStackExample.swift
> +        .avatarSize(self.avatarSize)
OK let's keep them as environment values. But at lease we can combine border width and color into one api. Same as SwiftUI's border modifier.

2024-09-09 00:57 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/AvatarStack/AvatarStackExample.swift
> +        .avatarSize(self.avatarSize)
Updated to `func avatarsBorder(_ color: Color, width: CGFloat = 1) -> some View`

2024-09-09 19:23 UTC, billzhou0223 approved these changes

2024-09-09 19:23 UTC, merged