feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2348] shadow effect api
SAP/cloud-sdk-ios-fiori pull request #791
Opened 2024-09-04 07:49 UTC by xiaoyu0722

New API `func shadow(_ style: FioriShadowStyle) -> some View`
<img src="https://github.com/user-attachments/assets/f8fc1f2d-2006-4122-a706-0d2b36fc5d76" width="40%"/>

2024-09-05 05:45 UTC, xiaoyu0722 commented
Any suggestions for shadow api are welcome.

2024-09-05 20:26 UTC, dyongxu commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +    let color1 = Color(white: 0, opacity: 0.13)
Does the spec say the color used here should be "white" ?  I think opacity on top of a "white" color may not create any visual effect.   Also, we need to consider dark mode. So base color should be a dynamic color , I assume. You can follow up with Designer on this.

2024-09-05 20:26 UTC, dyongxu approved these changes

2024-09-05 22:21 UTC, dyongxu requested changes
Shadow effect is almost invisible.

2024-09-05 23:57 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +    let color1 = Color(white: 0, opacity: 0.13)
Yes, all shadows are black(0 white) with opacity and same values for light and dark mode.
<img width="870" alt="Screenshot 2024-09-06 at 07 54 05" src="https://github.com/user-attachments/assets/3f6b2ffb-f57b-47cc-8932-dddb61d0b67a">

2024-09-06 22:12 UTC, billzhou0223 approved these changes

2024-09-07 02:05 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +    case broad
I suggest making the following changes to the case names to match the design guidelines more closely:
- `minimal`...`max` -> `level0`...`level4`
- `compact` -> `smallElement`
- `broad` -> `mediumElement`

2024-09-07 02:06 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +                .shadow(color: self.color2, radius: 32, y: 16)
The radius values for this shadow type should be 1, 8 and 16 according to the design spec

2024-09-09 20:58 UTC, JuliaSchnSAP commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +                .shadow(color: self.color2, radius: 32, y: 16)
To clarify my last comment I meant to change these two lines to the following code:
```
.shadow(color: self.color2, radius: 8, y: 8)
.shadow(color: self.color2, radius: 16, y: 16)
```

2024-09-09 23:25 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Utils/ShadowEffect.swift
> +                .shadow(color: self.color2, radius: 32, y: 16)
Sorry my mistake, all fixed.

2024-09-10 05:57 UTC, xiaoyu0722 commented
@dyongxu Need a review again.

2024-09-11 02:36 UTC, dyongxu approved these changes

2024-09-11 03:15 UTC, merged