feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2707] SwiftUI RatingControl Enhancement
SAP/cloud-sdk-ios-fiori pull request #794
Opened 2024-09-05 22:58 UTC by janhuachu

SwiftUI RatingControl enhancement with value label and review count label

✅ Closes: HCPSDKFIORIUIKIT-2707

2024-09-09 05:54 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
> +        case standardLarge
I'd like to use the `Bool` variable `isLarge` with the UIKit `FUIRatingControl`. By default, it is set to `false` for the read-only state and always `true` for the editable and disabled states. This approach is more simple to me when a smaller size is needed for the editable or disabled states, or for any new states that may be introduced in the future. For us, this means that we do not need to add too many styles, and for the App team, it makes it easy to understand that there are two sizes for each state. 
I just want to let you know about the difference between your API and mine. However, I am definitely okay with your implementation for these two new styles here for SWiftUI Rating Control.

2024-09-09 06:06 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlStyle.fiori.swift
> +            if configuration.showsValueLabel, self.getReadOnly(configuration) {
I am a little confused about the left value for the editable/disabled state. The design spec mentions 'Left value (optional) except for editable and disabled variants.'. From my understanding, this means that the left value is required/mandatory for the editable and disabled states. I have consulted the designer about this in Figma. 
There's a high probability that my understanding of the above sentence might be incorrect. But, just want to let you know this. :-)

2024-09-09 07:07 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlStyle.fiori.swift
> +            if configuration.showsValueLabel, !self.getReadOnly(configuration) {
Now, I understand the meaning of valueLabel and reviewCountLabel you always mentioned during our discussion But, for me, I would think it is the value concept for displaying on left and right. And, I feel it is not very straightforward. For example, here, if App team want to customize the value displayed on the right, they must to know when they should set the value for one of 'ratingValueFormat', 'averageRatingFormat', 'reviewCountFormat' and 'reviewCountCeilingFormat'. 

For me, I'd like to use more simple or straightforward logic on UIKit: To use two 'showXXXLabel' bool flag to control label display and use two 'XXXLabelFormat' for customization whatever we call it 'leftLabel/leadingLabel/valueLabel' or 'rightLabel/trailingLabel/reviewCountLabel'(Now, I use valueLabel and reviewCountLabel base on our discussion before). Absolutely, 'reviewCount' and 'reviewCountCeiling' were needed. Then, App team just to know there are two 'XXXLabelFormat' for customization and the default value for those two labels was that the label on left will use default formatted rating value or average rating value according to the style(confirming with designer about should display value for NON-readonly state). For the value of label on right, by default, to use '3 of 5' or '2.3 of 5' if there is no review count and use '9 review' or '8+ reviews' if there has reviewCount or reviewCount>reviewCountCeiling.

Certainly, I just want to let you know about the different between your API and mine. :-)

2024-09-09 07:09 UTC, JunSong-SH approved these changes
LGTM!

2024-09-09 13:25 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
> +            } else if diff < 0.7 {
See FIORITECHE1-8222, web component use 1.0-1.2 -> 1, 1.3-1.7 -> 1.5 and 1.8-1.9 -> 2. So, here, shouldn't diff <= 0.7 or diff < 0.8?

2024-09-09 16:52 UTC, janhuachu commented on Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
> +        case standardLarge
@JunSong-SH I was originally using the isLarge property. However, later I removed it to reduce the number of properties. I think there are too many properties already.

2024-09-09 17:02 UTC, janhuachu commented on Sources/FioriSwiftUICore/_FioriStyles/RatingControlStyle.fiori.swift
> +            if configuration.showsValueLabel, self.getReadOnly(configuration) {
@JunSong-SH I have not thought about the behavior you mentioned above. Let's wait for the designer to clarify the behavior.

2024-09-09 17:18 UTC, janhuachu commented on Sources/FioriSwiftUICore/DataTypes/RatingControl+DataType.swift
> +            } else if diff < 0.7 {
Yes, you're right. I'll change it.

2024-09-09 19:21 UTC, billzhou0223 requested changes

2024-09-09 19:21 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var halfImage: Image? { get }
Why are these `Image` properties not view builder? Like title, subtitles, those UI elements should be declared as view builder so that they become customizable.

2024-09-09 19:21 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var valueLabelColor: Color? { get }
I don't think these style props are needed, because we can customize them using style modifiers

```
RatingControl()
    .valueLabelStyle {
        ValueLabel($0)
            .font()
            .foregroundStyle()
    }
```

2024-09-09 20:19 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var halfImage: Image? { get }
OK. I'll change that.

2024-09-09 20:36 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var valueLabelColor: Color? { get }
OK. I'll change it. Thanks.

2024-09-11 23:23 UTC, billzhou0223 approved these changes

2024-09-12 02:43 UTC, merged