feat: 🎸 sort & filter enhancement part 2
SAP/cloud-sdk-ios-fiori pull request #820
Opened 2024-10-11 08:21 UTC by restaurantt

add listpick
when listPickerMode is set to .automatic
items display mode is according to options count:
[1-4] menu
[5-8] filter form cell
(8- list

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-11 at 16 08 58](https://github.com/user-attachments/assets/ba72b1d9-cc87-4e8c-b0ee-e16e2ed81e37)

2024-10-11 18:09 UTC, CharlesXu0488 commented
The attached screenshot seems a selection dialog used somewhere. The missing picture is how the dialog is shown? In other words, how the list picker looks like when it's associated with filter feedback bar or when it's mixed with other type of values in full configuration?
Other questions:
1. How the list picker is different from button based picker?
2. Is "empty" selection allowed?
3. Is multiple selection allowed?

And, can you provide information/link on requirements?

2024-10-12 00:45 UTC, restaurantt commented
> The attached screenshot seems a selection dialog used somewhere. The missing picture is how the dialog is shown? In other words, how the list picker looks like when it's associated with filter feedback bar or when it's mixed with other type of values in full configuration? Other questions:
> 
> 1. How the list picker is different from button based picker?
> 2. Is "empty" selection allowed?
> 3. Is multiple selection allowed?
> 4. Noticed "取消“, "搜索“, "Reset", and "Apply" are mixed. Why is that?
> 
> And, can you provide information/link on requirements?

Click feedBackbarItem shows the dialog.
Item's init func is almost same to the origin PickerItem, add 'listPickerMode' parameter.
1. It depends on 'listPickerMode', if the mode is automatic, it depends on the options count.
2. Yes, depends on item init configuration.
3. Yes, depends on item init configuration.
4. When I take the screenshot, "Reset", "apply" are not localized, and the search text field is provide by system 'searchable' to the NavigationStack.
I will attach links when I am in the office.

2024-10-14 23:48 UTC, CharlesXu0488 commented
> https://www.figma.com/design/malASExYGRLH4SWx7BVzZ1/Filter-Form-Cell%2FSegmented-Control?node-id=1867-3954&node-type=frame&t=99EAdMV9iXxH4L5X-0

Thanks for providing info and answers. Some further comments:
1. The spec does not provide styling (fonts and colors, etc.) info, so I am not sure the the fonts and colors in your impl are correct or not.
2. The "sheet" in your impl seems a "full" sheet and there is a big white space between list values and apply button. Previously, spec required "flexible" sheet. in other words, the sheet is high enough for containing the list and buttons, but not too high. It seems to my, design still wants "flexible" height of sheet.
3. How the list is handled if "full" configuration is invoked (from the "CFG(10)" button), as "chips"? I mean consistency. Or it will be future design?

2024-10-14 23:56 UTC, billzhou0223 requested changes

2024-10-14 23:56 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +        public var listPickerMode: OptionListPickerMode = .automatic
I will call it `DisplayMode` and make it a nested type of `PickerItem`

2024-10-14 23:56 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +public protocol OptionSearchListPickerItemModel: OptionListPickerComponent {
There is a existing component called `SeachableListView`. Can you reuse it in your use case?

Why does the name start with `Option`? It's redundant and confusing.

2024-10-14 23:56 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Views/SortFilter/FilterFeedbackBarItem+View.swift
> +public enum OptionListPickerMode {
I will call it `DisplayMode` and make it a nested type of `PickerItem`

2024-10-15 00:54 UTC, restaurantt commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +public protocol OptionSearchListPickerItemModel: OptionListPickerComponent {
I have looked into `SeachableListView`, I think it can not be reused here. I name this according to `OptionListPickerItemModel`. Please give me a suggestion.

2024-10-15 08:58 UTC, restaurantt commented
I have some code optimization to commit, and some details to check with the designer. Please review after my next commit.

2024-10-16 09:26 UTC, restaurantt commented
> > https://www.figma.com/design/malASExYGRLH4SWx7BVzZ1/Filter-Form-Cell%2FSegmented-Control?node-id=1867-3954&node-type=frame&t=99EAdMV9iXxH4L5X-0
> 
> Thanks for providing info and answers. Some further comments:
> 
> 1. The spec does not provide styling (fonts and colors, etc.) info, so I am not sure the the fonts and colors in your impl are correct or not.
> 2. The "sheet" in your impl seems a "full" sheet and there is a big white space between list values and apply button. Previously, spec required "flexible" sheet. in other words, the sheet is high enough for containing the list and buttons, but not too high. It seems to me, design still wants "flexible" height of sheet.
> 3. How the list is handled if "full" configuration is invoked (from the "CFG(10)" button), as "chips"? I mean consistency. Or it will be future design?
> 4. Spec did not specify iPad case, can you provide a screenshot for iPad?
> 
> You might want to check with designer. I wish I could figure out who is the designer and talk to him/her on your behalf.

Checked some details with the designer Escutia, Max
1. I used fonts and colors in figma and they are correct. 
2. The display mode can be set or automatically. When intentionally set mode to list and count of options is for example 3, designer says  it's ok.
3. I take a screenshot. And here display mode changes to 2 mode, count range 1 to 8 is filterFormCell and greater than 8 is list.
4. iPad screenshot is taken, too.

2024-10-16 09:29 UTC, restaurantt commented
@CharlesXu0488 @billzhou0223 Please continue to review. Thanks.

2024-10-16 18:01 UTC, CharlesXu0488 commented
> > > https://www.figma.com/design/malASExYGRLH4SWx7BVzZ1/Filter-Form-Cell%2FSegmented-Control?node-id=1867-3954&node-type=frame&t=99EAdMV9iXxH4L5X-0
> > 
> > 
> > Thanks for providing info and answers. Some further comments:
> > 
> > 1. The spec does not provide styling (fonts and colors, etc.) info, so I am not sure the the fonts and colors in your impl are correct or not.
> > 2. The "sheet" in your impl seems a "full" sheet and there is a big white space between list values and apply button. Previously, spec required "flexible" sheet. in other words, the sheet is high enough for containing the list and buttons, but not too high. It seems to me, design still wants "flexible" height of sheet.
> > 3. How the list is handled if "full" configuration is invoked (from the "CFG(10)" button), as "chips"? I mean consistency. Or it will be future design?
> > 4. Spec did not specify iPad case, can you provide a screenshot for iPad?
> > 
> > You might want to check with designer. I wish I could figure out who is the designer and talk to him/her on your behalf.
> 
> Checked some details with the designer Escutia, Max
> 
> 1. I used fonts and colors in figma and they are correct.
> 2. The display mode can be set or automatically. When intentionally set mode to list and count of options is for example 3, designer says  it's ok.
> 3. I take a screenshot. And here display mode changes to 2 mode, count range 1 to 8 is filterFormCell and greater than 8 is list.
> 4. iPad screenshot is taken, too.

Thanks for iPad screenshots and info from designer. Is Max OK with "full" sheet instead of "flexible" sheet of the second screenshot?

2024-10-17 04:52 UTC, restaurantt commented
> > > > https://www.figma.com/design/malASExYGRLH4SWx7BVzZ1/Filter-Form-Cell%2FSegmented-Control?node-id=1867-3954&node-type=frame&t=99EAdMV9iXxH4L5X-0
> > > 
> > > 
> > > Thanks for providing info and answers. Some further comments:
> > > 
> > > 1. The spec does not provide styling (fonts and colors, etc.) info, so I am not sure the the fonts and colors in your impl are correct or not.
> > > 2. The "sheet" in your impl seems a "full" sheet and there is a big white space between list values and apply button. Previously, spec required "flexible" sheet. in other words, the sheet is high enough for containing the list and buttons, but not too high. It seems to me, design still wants "flexible" height of sheet.
> > > 3. How the list is handled if "full" configuration is invoked (from the "CFG(10)" button), as "chips"? I mean consistency. Or it will be future design?
> > > 4. Spec did not specify iPad case, can you provide a screenshot for iPad?
> > > 
> > > You might want to check with designer. I wish I could figure out who is the designer and talk to him/her on your behalf.
> > 
> > 
> > Checked some details with the designer Escutia, Max
> > 
> > 1. I used fonts and colors in figma and they are correct.
> > 2. The display mode can be set or automatically. When intentionally set mode to list and count of options is for example 3, designer says  it's ok.
> > 3. I take a screenshot. And here display mode changes to 2 mode, count range 1 to 8 is filterFormCell and greater than 8 is list.
> > 4. iPad screenshot is taken, too.
> 
> Thanks for iPad screenshots and info from designer. Is Max OK with "full" sheet instead of "flexible" sheet of the second screenshot?

Yes, he is ok with this.
The list picker in the sheet opened by clicking 'CFG(10)' need a modification, so I need do more changes.
<img width="816" alt="截屏2024-10-17 12 51 34" src="https://github.com/user-attachments/assets/a9e09cdf-af5a-43f6-9cfe-94dd6da13a26">

2024-10-17 16:47 UTC, CharlesXu0488 approved these changes
Please work with Bill on his change request. For the rest, your answers to my questions and concerns look good.

2024-10-17 23:06 UTC, billzhou0223 approved these changes

2024-10-17 23:06 UTC, merged