feat: 🎸 [JIRA: HCPSDKFIORIUIKIT-2764] list picker enhancement
SAP/cloud-sdk-ios-fiori pull request #823
Opened 2024-10-14 09:35 UTC by xiaoyu0722

| Debug Panel | Normal Single Selection | Multiple Selections |
| --- | --- | --- |
|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 00 09](https://github.com/user-attachments/assets/34666495-6d36-4413-80c1-56075574ac37)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 25 36](https://github.com/user-attachments/assets/d54c2c5b-7a8f-4120-8091-2fa57d161270)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 25 49](https://github.com/user-attachments/assets/76efc211-394b-465f-bb44-ba614e8ef6f6)|

| Search | Filter | Cancel Alert | Customizaiton |
| --- | --- | --- | --- |
|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 26 02](https://github.com/user-attachments/assets/bec9eaf5-a337-452b-b90f-de0038683b12)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 26 19](https://github.com/user-attachments/assets/1259ca45-b875-4e4d-8bdf-5e7c5355402c)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 26 54](https://github.com/user-attachments/assets/e84e4ca4-32be-4928-a045-c2a0f23afda8)|![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-14 at 17 27 09](https://github.com/user-attachments/assets/ea15108d-6d75-41c3-bca8-6bf37e732e97)|

2024-10-14 22:44 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// `ListPickerItem` is a view that provide a `NavigationLink` with a title and selected value. And `ListPickerDestination` is recommended to be used as its destination, which selection, search filte
```suggestion
/// `ListPickerItem` is a view that provides a `NavigationLink` with a title and selected value(s). And `ListPickerDestination` is recommended to be used as its destination, for which selection, search filter and customized rows are supported.
```

2024-10-14 23:15 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +struct ListPickerItemExample: View {
In UIKit, the list picker can group some values in sections. 
e.g.
Section 1 for all apples
Section 2 for all pears
Section 3 for all grapes

Currently, looks like only "Selected" and "All" section are supported. 
Do this new implementation support multiple "group" idea as well ? If yes, can we add some new cases?

2024-10-14 23:15 UTC, dyongxu requested changes
comments inlined

2024-10-15 00:28 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +struct ListPickerItemExample: View {
Currently, not support different groups, I will check again and see how to make it works.

2024-10-15 20:59 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
> +public struct ListPickerDestinationContent<Data: RandomAccessCollection, ID: Hashable, RowContent: View>: View {
Do developers need to have access to this type? If not we can make it internal.

2024-10-15 20:59 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
In your example, developers need to observe selection changes and construct the value view by themselves. This is good because it's very customizable. In addition to that, do you also provide a default implementation for building the value view in SDK so that this component becomes more convenient to use? For example, the default value view in the simplest form could be concatenating the ids of selected items.

2024-10-17 01:19 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_FioriStyles/ListPickerDestinationStyle.fiori.swift
> +public struct ListPickerDestinationContent<Data: RandomAccessCollection, ID: Hashable, RowContent: View>: View {
No, I will remove public statement.

2024-10-17 01:24 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Emm, api takes id as an identifier. I'm not sure if it's a good idea to take it to generate a default value view.
The example use a separate `valueView` is for different cases, like optional/empty/multiple values.

2024-10-17 23:15 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Maybe using id is not good. How about introduce a new param `name: KeyPath<Data.Element, String>?` in `ListPickerDestination`'s init which can be used as default selection name. 

I think we need to provide a default value view according to spec.

2024-10-17 23:30 UTC, dyongxu approved these changes

2024-10-17 23:31 UTC, dyongxu commented
@xiaoyu0722 Need to resolve merge conflict issue.

2024-10-21 02:22 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Hi @billzhou0223 Any other issue? I will merge first if no other problem.

2024-10-22 19:40 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
If we don't have a default implementation, how can you ensure the component's value field matches the spec? Having the developers to create the value view on their own and set the required UI properties like font, color, accessibility attributes, etc according to spec is not realistic and it deviates the purpose of providing it as a SDK component.

What you need is a way to communicate between different components and I can think of several on the top of my head like callback, pub-sub (Combine), notification (not recommended), etc.

2024-10-23 06:01 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Is this not the purpose of styleable template that allow customization?
If they just a clean text used for value component, then fiori style will be applied. If not, then it's up to developer?

2024-10-24 00:49 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Of course customization is important and that's well supported currently with the new architecture. But in addition to that, SDK component should provide convenience and allow developers to achieve more by doing less. Based on the common use case of this component, it's easy to understand that the value is always constructed from the selected items so why don't we provide a default implementation to help developers take care of this tedious work? It could be simply a text as you said but it could also be something else more complicated (designers wanted to replace them with [chips](https://www.figma.com/design/OKmSSho6WyEL7c4sWiIqXc/List-Picker-Form-Cell-(iOS)?node-id=1-18&node-type=canvas&t=bZ6DLLgGjGuEMRvh-0) before but we didn't implement it). Having this default implementation in place allows us to adapt to future design changes more easily. Hope this makes sense.

2024-10-24 09:31 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Hi @billzhou0223 
A default `Text` is added when value is empty in last commit.
But there is a problem, that developer can not use `.valueStyle {}` to modify its style when they do not give a value view.

2024-10-24 23:54 UTC, billzhou0223 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
I think you need to wrap the default view with a `Value` view.

2024-10-25 01:32 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/FormCells/ListPickerItemExample.swift
> +                self.valueView
Fixed.

2024-10-25 20:06 UTC, billzhou0223 approved these changes

2024-10-25 20:06 UTC, merged