feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2717] Feedback Patterns
SAP/cloud-sdk-ios-fiori pull request #826
Opened 2024-10-16 06:39 UTC by hengyi-zhang

Title and icon support developer customization in banner message

2024-10-16 23:39 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
> +            Icon(configuration)
Why we change the default color to be negativeLabel , for icon, title, etc?
Originally, the default color is based on messageType, which looks good to me.
I think, to allow the customization, the enhancement is to allow developer to override the default color for different messageType.

2024-10-16 23:40 UTC, dyongxu requested changes
some question inlined.

2024-10-17 01:14 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMessageStyle.fiori.swift
> +            Icon(configuration)
It's the default logic before feedback patterns. I just restore the code to the node before feedback patterns.

2024-10-17 23:18 UTC, billzhou0223 approved these changes

2024-10-17 23:29 UTC, dyongxu approved these changes

2024-10-21 17:18 UTC, merged