refactor: 💡 size and frame reader
SAP/cloud-sdk-ios-fiori pull request #829
Opened 2024-10-21 06:57 UTC by xiaoyu0722

2024-10-22 19:09 UTC, billzhou0223 requested changes

2024-10-22 19:09 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +        onGeometryChange(for: CGRect.self) { proxy in
This is a iOS 18 only API. But we still need to support iOS 17.

2024-10-22 23:31 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/Experimental/Popover/View+Extension.swift
> +        onGeometryChange(for: CGRect.self) { proxy in
Found this API works in iOS 17. Close this comment

2024-10-22 23:31 UTC, billzhou0223 approved these changes

2024-10-25 20:07 UTC, billzhou0223 commented
@xiaoyu0722 Is this PR complete? If so please remove the `do not merge` tag.

2024-10-28 00:04 UTC, xiaoyu0722 commented
`onGeometryChange` needs swift 6.0. So I will close this PR and reopen it when ci tool is update to Xcode 16.

2024-10-28 00:04 UTC, closed without merging