Feat/hcpsdkfiori UI kit 2717
SAP/cloud-sdk-ios-fiori pull request #830
Opened 2024-10-22 03:00 UTC by hengyi-zhang

2024-10-22 18:29 UTC, dyongxu approved these changes

2024-10-22 19:05 UTC, billzhou0223 requested changes

2024-10-22 19:05 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
Why does this public component not built with component protocols?

2024-10-22 19:05 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                    .ifApply(true, content: { v in
Why use `ifApply` if the condition is always true?

2024-10-22 19:05 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                            c.icon.foregroundStyle(BannerMessageFioriStyle.titleForegroundColor(type: message.messageType))
Customizing style like this will make style composition not work. Better way is 

`Icon(configuration).foregroundStyle(...)`

2024-10-23 03:09 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                    .ifApply(true, content: { v in
Banner message sheet pops from the top banner message and nested under the title of the top banner message. 
Banner message sheet reuses several banner message items. In view of the little components in the top banner message use global universal environment key, like \.iconStyle, \.titleStyle, etc. The style of the top banner message will affect the banner message's style in the sheet. So here uses the .ifApply modifier to get the configuration of each banner message to reconfiguration the style which affected by top banner message.

2024-10-24 00:17 UTC, billzhou0223 requested changes

2024-10-24 00:17 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
You can still build `BannerMessageSheet` with the new pattern even if a sub-component is a legacy component. You just need to clearly define the properties of `BannerMessageSheet` in protocols. You are not even exposing any properties of dimension selector in this component so it shouldn't affect you at all.

2024-10-24 00:17 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                    .ifApply(true, content: { v in
I am not sure if the banner sheet is a subview of top banner. It looks weird to me. Anyway, I am wondering why you use `ifApply` to configure the icon style instead of doing something simpler. Aren't they the same?

```
BannerMessage()
    .iconStyle(...)
```

2024-10-30 08:44 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
fixed!

2024-10-30 08:44 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                    .ifApply(true, content: { v in
fixed!

2024-10-30 08:45 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/BannerMultiMessageSheet.fiori.swift
> +                                            c.icon.foregroundStyle(BannerMessageFioriStyle.titleForegroundColor(type: message.messageType))
fixed!

2024-10-31 21:25 UTC, billzhou0223 requested changes

2024-10-31 21:25 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    // sourcery: @ViewBuilder
The type is already a closure, so the annotation should be `@ViewBuilder` instead of `// sourcery: @ViewBuilder`.

The template needs to be adjusted accordingly.

2024-11-04 05:53 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    // sourcery: @ViewBuilder
fixed!

2024-11-04 19:27 UTC, billzhou0223 approved these changes
Thanks

2024-11-05 03:41 UTC, dyongxu approved these changes

2024-11-05 14:09 UTC, merged