feat: 🎸 [HCPSDKFIORIUIKIT-2791]SwiftUI: floating value support
SAP/cloud-sdk-ios-fiori pull request #834
Opened 2024-10-24 08:01 UTC by zzchao-1999

<img width="316" alt="Screenshot 2024-10-18 at 17 14 37" src="https://github.com/user-attachments/assets/ce77f9b3-d6ea-4298-b006-2c489e4bbcfc">

2024-10-24 23:28 UTC, billzhou0223 requested changes

2024-10-24 23:28 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var stepRange: ClosedRange<Double> { get }
How do I control the interval of the stepper?

2024-10-25 00:11 UTC, zzchao-1999 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var stepRange: ClosedRange<Double> { get }
Did you mean the increment/decrement size? If so, you can use the "step" parameter.
var step: Double { get }

2024-10-28 07:49 UTC, zzchao-1999 commented
> We may need to enhance the display of number of decimals in the StepperField. e.g. if you have a range of 0 to 1.0, and stepper value is 0.1, when you increase/decrease, you may see values as "0.6999999999999". This is due to "Double" is used as the new data type. One suggestion could be, we can check the stepper value. Then use the same number of decimals, to format the StepperField value

Added a number formatter to ensure the display of number of decimals in the stepperField.

2024-10-28 18:30 UTC, dyongxu approved these changes

2024-10-28 19:42 UTC, billzhou0223 approved these changes

2024-10-28 21:53 UTC, dyongxu commented
@zzchao-1999 Check with the reporter if it is needed for rel-4.1

2024-10-28 21:53 UTC, merged