feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2796]Loading Indicator
SAP/cloud-sdk-ios-fiori pull request #842
Opened 2024-10-28 05:44 UTC by KevinZK

2024-10-28 20:30 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +            LoadingIndicatorView(title: "will dismiss after 3 second", duration: 3, isPresented: self.$isPresented1)
1. We need a test for the default behavior of Loading Indicator. So, remove the indicatorPosition, indicatorTint, indicatorScaleEffect for this case (line 16  to 18). 
2. Update the duration "3" to "10" so it shows longer. 
3. Add a toggle button to hide/unhide the indicator.

2024-10-28 20:34 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +                Button("show Loading Indicator") {
```suggestion
                Button("Show/Hide Loading Indicator") {
```

2024-10-28 20:40 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +            LoadingIndicatorView(title: "Loading...", isPresented: self.$isPresented3)
Add a case for .leading indicatorPosition. 
Then group the four cases ( .leading, .trailing, .top, .bottom ), into one section, with a header, called "Supported Layout for Loading Indicator).  It will be easy for the user to understand these 4 are for the layout testig.

2024-10-28 20:58 UTC, dyongxu requested changes
comments embedded.

2024-10-29 17:01 UTC, dyongxu commented
@angiexyang  This PR uses the native ProgressView as well. Can you also review this as well, to see if any consistency issue needs to be addressed ?

2024-10-29 17:27 UTC, angiexyang commented
> @angiexyang This PR uses the native ProgressView as well. Can you also review this as well, to see if any consistency issue needs to be addressed ?

ProgressIndicator doesn't use the native ProgressView, since ProgressView only shows the indeterminate ticker on iOS.

2024-10-29 18:08 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +                        LoadingIndicatorView(title: "mini size", isPresented: self.$isPresented3)
```suggestion
                        LoadingIndicatorView(title: "mini size indicator", isPresented: self.$isPresented3)
```

2024-10-29 18:09 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +                            Text("small size")
```suggestion
                            Text("small size indicator")
```

2024-10-29 18:09 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +                                Text("extraLarge size")
```suggestion
                                Text("extraLarge size indicator")
```

2024-10-29 18:10 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/Indicator/LoadingIndicatorExample.swift
> +                        LoadingIndicatorView(title: "large size", isPresented: self.$isPresented6)
```suggestion
                        LoadingIndicatorView(title: "large size indicator", isPresented: self.$isPresented6)
```

2024-10-29 18:13 UTC, dyongxu requested changes
comments inlined.
Also, re-order the indicator size test code, based on its size, by mini, small, large, extra large.

2024-10-31 14:52 UTC, dyongxu approved these changes

2024-11-05 03:42 UTC, merged