feat: 🎸 HCPSDKFIORIUIKIT-2709 Enhancement: Document Scanning
SAP/cloud-sdk-ios-fiori pull request #850
Opened 2024-10-31 03:23 UTC by zzchao-1999

<img width="658" alt="Screenshot 2024-10-31 at 09 23 33" src="https://github.com/user-attachments/assets/e0a77296-80a8-4fc2-aa09-c569820a207a">
<img width="655" alt="Screenshot 2024-10-31 at 09 27 05" src="https://github.com/user-attachments/assets/4bffcf57-1c85-4f37-8b06-ad0da39ba10e">
<img width="655" alt="Screenshot 2024-10-31 at 09 29 26" src="https://github.com/user-attachments/assets/ab721893-173c-4dac-b7cb-1c9d11f54697">

2024-10-31 23:31 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
> +                    destination: DocumentScannerViewExample())
DocumentScannerViewExample.swift needs to be added the Apps/Examples/Examples.xcodeproj . Otherwise, the sample App will not compile.

2024-10-31 23:35 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +}
Is it doable to add some additional test here, to allow the end user to save the "Scanned Results" to the local phone ? (Photo, or Files) This will show the App developer the scanned result is available, and they can choose do whatever they want to do.

2024-11-01 00:01 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +}
App team may want to see the pages horizontally, or vertically. So we need to have the option for PDFKitView.

2024-11-01 00:02 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +struct PDFKitView: UIViewRepresentable {
Also , suggest to rename PDFKitView , to PDFView

2024-11-01 00:02 UTC, dyongxu requested changes
comments inlined

2024-11-04 03:02 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/CoreContentView.swift
> +                    destination: DocumentScannerViewExample())
Checked in the updated file.

2024-11-04 03:07 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +}
The possible output types: either an array of images or a PDF document, app dev can handle them further.

2024-11-04 03:10 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +}
Updated sample code, show images horizontally, show pdf vertically.

2024-11-04 03:11 UTC, zzchao-1999 commented on Apps/Examples/Examples/FioriSwiftUICore/DocumentScannerView/DocumentScannerViewExample.swift
> +struct PDFKitView: UIViewRepresentable {
Renamed it.

2024-11-04 19:52 UTC, dyongxu approved these changes

2024-11-04 23:46 UTC, merged