fix: 🐛 IOSSDKBUG-430 Fiori FilterFeedbackBar enhancement
SAP/cloud-sdk-ios-fiori pull request #853
Opened 2024-10-31 18:41 UTC by xiaoqinggrace

Feature change request for showing the label when there is a single item selected.
Based on the requirement, change the showsValueForSingleSelected to singleSelectedMode. This will allow the Filter Feedback Bar label to show the name, value, or name and value when a single item is selected.
<img width="561" alt="fixedFilterFeedbackBar" src="https://github.com/user-attachments/assets/9db07736-44f4-4527-bc2f-7cf705c0a18c">

2024-10-31 21:03 UTC, billzhou0223 requested changes

2024-10-31 21:03 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> -        public var showsValueForSingleSelected: Bool = true
Use @available keyword to deprecate a public attribute.

2024-10-31 21:03 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +        public enum SingleSelectedMode {
Suggest calling it `barItemDisplayMode`

2024-10-31 21:03 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +            case showNameValue
Change to 

```
            case name
            /// To show the value
            case value
            /// To show both the name and value
            case nameAndValue
```

2024-10-31 21:55 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +        /// Enum for display modes of the filter feed bar label when a single item selected
```suggestion
        /// Enum for display mode of the FilterFeedbackBar item when only one value is selected for that item
        /// This is effective, regardless of that item allowing multiple selection or not
```

2024-10-31 21:56 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +        public enum SingleSelectedMode {
```suggestion
        public enum SingleValueDisplayMode {
```

2024-10-31 21:59 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +            case showNameValue
```suggestion
            /// To show the name only
            case showNameOnly
            /// To show the value only
            case showValueOnly
            /// To show both the name and value
            case showNameAndValue
```

2024-10-31 22:06 UTC, dyongxu requested changes
1. Comments inlined
2. May need to add some doc what is the default behavior regarding single value selection mode. I assume the default is "NameAndValue", sth like "To-Do(1)

2024-10-31 22:07 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +                    return self.name + ":" + self.valueOptions[self.value[0]]
```suggestion
                    return self.name + ": " + self.valueOptions[self.value[0]]
```

2024-11-01 04:41 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> -        public var showsValueForSingleSelected: Bool = true
Based on the feature request, showsValueForSingleSelected was added three weeks ago. There is no new build for rel-4.1 after it was added.

2024-11-01 04:59 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +        public enum SingleSelectedMode {
Bill also suggested the name. Which one should I follow?

2024-11-01 05:00 UTC, xiaoqinggrace commented on Sources/FioriSwiftUICore/DataTypes/SortFilter+DataType.swift
> +            case showNameValue
Bill also suggested the change. Which one should I follow?

2024-11-01 16:23 UTC, dyongxu approved these changes

2024-11-01 19:33 UTC, billzhou0223 approved these changes

2024-11-01 21:51 UTC, merged