fix: 🐛 [JIRA:IOSSDKBUG-375] TextInput Fom View a11y fix 2
SAP/cloud-sdk-ios-fiori pull request #854
Opened 2024-10-31 22:49 UTC by janhuachu

✅ Closes: IOSSDKBUG-375

2024-11-01 19:31 UTC, billzhou0223 requested changes

2024-11-01 19:31 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var actionIconAccessibilityLabel: String? { get }
My thinking:

1. TextFieldFormView should conform to `ActionComponent` instead of exposing a `actionIcon` property.
2. The accessibility label should be applied to action button instead of action icon. And developers can set it using `actionStyle` modifier so we don't need to expose this property. Providing accessibility label property in a component is not scalable and maintainable.

2024-11-01 23:04 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var actionIconAccessibilityLabel: String? { get }
I will try to make it ActionComponent. However, when I added Button to the view, my experience is that the whole view become the touch area for the Button that user could not edit the TextField. I think this is SwiftUI problem.

2024-11-04 19:26 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var actionIconAccessibilityLabel: String? { get }
I believe the button will only appear on the trailing side of the field so it should not cover the entire input field.

2024-11-04 21:29 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var actionIconAccessibilityLabel: String? { get }
I originally use SwiftUI's Button and I observe the behavior that the entire view is the touch area of the Button. I need to chage it to an Image and add a onTapGesture to get the correct behavior.

When I use ActionComponent, I need to get the action block from the ActionComponent to invoke the action. I have yet to be able to get the action block from the ActionComponent. Do you have any idea how to do that?

2024-11-04 22:39 UTC, janhuachu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var actionIconAccessibilityLabel: String? { get }
Just tried a simple example:

`    var body: some View {
        List {
            HStack {
                Text("Test")
                Button("Button") {
                    print("*** Hello World!")
                }
            }
        }
    }
`
When tap "Text" the button action is also triggered.

2024-11-05 23:36 UTC, billzhou0223 approved these changes

2024-11-06 00:09 UTC, merged