feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2700] Object Cell Enhancement
SAP/cloud-sdk-ios-fiori pull request #877
Opened 2024-11-12 07:47 UTC by hengyi-zhang

2024-11-12 23:24 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCellEnhancementExample.swift
> +        .navigationTitle("Object Cell Enhancement")
```suggestion
        .navigationTitle("Object Cell Enhancement for Button")
```

2024-11-12 23:24 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectItemExample.swift
> +                Text("Object Cell Enhancement")
```suggestion
                Text("Object Cell Enhancement for Button")
```

2024-11-12 23:31 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCellEnhancementExample.swift
> +                FioriButton(title: "Label", action: { _ in
```suggestion
                FioriButton(title: "Buton", action: { _ in
```

2024-11-12 23:32 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCellEnhancementExample.swift
> +                FioriButton(title: "Label", action: { _ in
```suggestion
                FioriButton(title: "Button", action: { _ in
```

2024-11-12 23:32 UTC, dyongxu commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCellEnhancementExample.swift
> +                FioriButton(title: "Label", action: { _ in
```suggestion
                FioriButton(title: "Button", action: { _ in
```

2024-11-12 23:36 UTC, dyongxu requested changes
1. I suggested some test code change. Pls don't commit that directly from github(It will fail the build since the direct commit does not include a keyword in the commit message)
2. Can you review the screen with Xiaoyu to see if the "overflow" button alignment is correct? (It does not look correct to me)

2024-11-12 23:37 UTC, dyongxu commented
<img width="606" alt="Screenshot 2024-11-12 at 15 33 13" src="https://github.com/user-attachments/assets/8ffa9bb9-598f-47d9-b0ab-a4b29ad93409">
@hengyi-zhang @xiaoyu0722 Can you review the overflow button alignment is correct ?

2024-11-13 00:11 UTC, billzhou0223 requested changes

2024-11-13 00:11 UTC, billzhou0223 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var objectItemButton: FioriButton? { get }
What's this button used for?

An action usually should have its own component protocol like `ActionComponent`.

2024-11-13 02:13 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +    var objectItemButton: FioriButton? { get }
The objectItemButton for accessory enhancement

2024-11-13 02:30 UTC, hengyi-zhang commented on Apps/Examples/Examples/FioriSwiftUICore/ObjectItem/ObjectCellEnhancementExample.swift
> +        .navigationTitle("Object Cell Enhancement")
fixed!

2024-11-13 06:02 UTC, xiaoyu0722 commented
> @xiaoyu0722 Can you review the overflow button alignment is correct ?

No problem for the alignment.
Spec ask for the trailing alignment, also contain the button margin.
<img width="276" alt="Screenshot 2024-11-13 at 14 01 53" src="https://github.com/user-attachments/assets/705d1f08-e168-4c22-9470-fa2c3766c76e">

2024-11-15 01:51 UTC, dyongxu approved these changes

2024-11-18 15:46 UTC, dyongxu commented
@billzhou0223 We need to sync up with SAPFiori 24.12 for main codeline. Is there some requested change here? Or it is ok to merge ?

2024-11-19 02:51 UTC, merged