fix: 🐛 [IOSSDKBUG-455] FilterFeedbackBar maxWidth customization
SAP/cloud-sdk-ios-fiori pull request #878
Opened 2024-11-12 09:12 UTC by restaurantt

Add 'maxWidth' in 'filterFeedbackBarStyle'.

2024-11-12 14:40 UTC, dyongxu requested changes
Add a test case in TestApp, to show this behavior

2024-11-13 00:08 UTC, billzhou0223 approved these changes

2024-11-13 01:02 UTC, restaurantt commented
turn on the Custom Style switch at the bottom, it will active the custom style.
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-13 at 08 58 26](https://github.com/user-attachments/assets/fe6edc63-4b23-4f9a-b089-1c06123f21f4)

2024-11-13 02:16 UTC, dyongxu approved these changes

2024-11-13 02:16 UTC, merged