feat: 🎸 [JIRA:HCPSDKFIORIUIKIT-2880] ActivityItemModel Refactor
SAP/cloud-sdk-ios-fiori pull request #928
Opened 2024-12-06 09:49 UTC by hengyi-zhang

2024-12-06 14:32 UTC, dyongxu requested changes
I saw in the FioriIcons/Resources, some files were updated, (Contents.json).
Usually, we don't update these files under Resource folder, since these files are delivered by Designer team.  
Is there some specific reason why we have to update them here ?

2024-12-07 00:36 UTC, angiexyang commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +
Could you add some documentation and example code usage?

2024-12-09 01:08 UTC, hengyi-zhang commented
> I saw in the FioriIcons/Resources, some files were updated, (Contents.json). Usually, we don't update these files under Resource folder, since these files are delivered by Designer team. Is there some specific reason why we have to update them here ?

fixed!

2024-12-09 01:16 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +
fixed!

2024-12-09 19:06 UTC, xiaoqinggrace commented
For the generated code, we do not need to commit if there is no change even if the order of the generated code is different.

2024-12-09 21:32 UTC, dyongxu commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +@available(*, unavailable, renamed: "_ActivityItemModel", message: "Will be removed in the future release. Please create ActivityItemModel with other initializers instead.")
```suggestion
@available(*, unavailable, renamed: "_ActivityItemModel", message: "Will be removed in the future release. Please create ActivityItem with other initializers instead.")
```

2024-12-10 00:22 UTC, billzhou0223 approved these changes

2024-12-10 01:18 UTC, KevinZK approved these changes

2024-12-10 01:41 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/Models/ModelDefinitions.swift
> +@available(*, unavailable, renamed: "_ActivityItemModel", message: "Will be removed in the future release. Please create ActivityItemModel with other initializers instead.")
fixed!

2024-12-12 04:05 UTC, dyongxu approved these changes

2024-12-13 18:07 UTC, merged