feat: 🎸 HCPSDKFIORIUIKIT-2812 SwiftUI KPIProgressItem refactor
SAP/cloud-sdk-ios-fiori pull request #936
Opened 2024-12-11 07:10 UTC by zzchao-1999

| All | Percentage | Fraction|
| --- | --- | --- |
|<img width="345" alt="Screenshot 2024-12-11 at 01 06 44" src="https://github.com/user-attachments/assets/0eec9664-543b-4d19-b4de-bf0d75ea1032">|<img width="343" alt="Screenshot 2024-12-11 at 01 07 07" src="https://github.com/user-attachments/assets/6df5df85-f5de-4cd0-8689-d1554839fc76">|<img width="345" alt="Screenshot 2024-12-11 at 01 07 42" src="https://github.com/user-attachments/assets/23fada2c-b2fd-47e3-afc2-4162c0f9dd9b">|

2024-12-12 04:22 UTC, dyongxu commented
@KevinZK Can you review it from "NSS" support perspective, if this refactoring code is ready for the future NSS enhancement?

2024-12-12 06:15 UTC, KevinZK commented
Based on the NSS features I have designed so far, I make some suggestions:
For this component to fully support the NSS style, you need to split the KPIProgressItem component as much as possible.
For example, we can split KPIProgressItem into three components _TitleComponent, _SubtitleComponent, and _circleProgressComponent.
After designing like this, the configuration code for NSS will be generated in the ~style.fiori.swift file.
```swift
extension KPIProgressItemNSSStyle {
    struct ContentNSSStyle: KPIProgressItemStyle {
        let kpiProgressItemConfiguration: KPIProgressItemConfiguration
        let nssData: NSSStyleData
        func makeBody(_ configuration: KPIProgressItemConfiguration) -> some View {
            KPIProgressItem(configuration)
                .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
            // Add custom nss style for its content
            // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
        }
    }

    struct TitleNSSStyle: TitleStyle {
         let kpiProgressItemConfiguration: KPIProgressItemConfiguration
        let nssData: NSSStyleData

        func makeBody(_ configuration: TitleConfiguration) -> some View {
            Title(configuration)
                .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
            // Add custom nss style for Title
            // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
        }
    }

struct SubtitleNSSStyle: TitleStyle {
         let kpiProgressItemConfiguration: KPIProgressItemConfiguration
        let nssData: NSSStyleData

        func makeBody(_ configuration: SubtitleConfiguration) -> some View {
            Title(configuration)
                .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
            // Add custom nss style for Title
            // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
        }
    }

    struct CircleProgressNSSStyle: ProgressStyle {
        let kpiProgressItemConfiguration: KPIProgressItemConfiguration
        let nssData: NSSStyleData

        func makeBody(_ configuration: CircleProgressConfiguration) -> some View {
            CircleProgress(configuration)
                .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
            // Add custom nss style for Progress
            // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
        }
    }
}
```
Since my current pull request is still under review, for reference only.

2024-12-19 22:54 UTC, dyongxu commented
@zzchao-1999  Some merge conflict to be resolved

2024-12-20 14:24 UTC, dyongxu requested changes
Resolve merge conflict

2025-01-06 13:40 UTC, zzchao-1999 commented
> Based on the NSS features I have designed so far, I make some suggestions: For this component to fully support the NSS style, you need to split the KPIProgressItem component as much as possible. For example, we can split KPIProgressItem into three components _TitleComponent, _SubtitleComponent, and _circleProgressComponent. After designing like this, the configuration code for NSS will be generated in the ~style.fiori.swift file.
> 
> ```swift
> extension KPIProgressItemNSSStyle {
>     struct ContentNSSStyle: KPIProgressItemStyle {
>         let kpiProgressItemConfiguration: KPIProgressItemConfiguration
>         let nssData: NSSStyleData
>         func makeBody(_ configuration: KPIProgressItemConfiguration) -> some View {
>             KPIProgressItem(configuration)
>                 .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
>             // Add custom nss style for its content
>             // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
>         }
>     }
> 
>     struct TitleNSSStyle: TitleStyle {
>          let kpiProgressItemConfiguration: KPIProgressItemConfiguration
>         let nssData: NSSStyleData
> 
>         func makeBody(_ configuration: TitleConfiguration) -> some View {
>             Title(configuration)
>                 .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
>             // Add custom nss style for Title
>             // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
>         }
>     }
> 
> struct SubtitleNSSStyle: SubtitleStyle {
>          let kpiProgressItemConfiguration: KPIProgressItemConfiguration
>         let nssData: NSSStyleData
> 
>         func makeBody(_ configuration: SubtitleConfiguration) -> some View {
>             Subtitle(configuration)
>                 .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
>             // Add custom nss style for Subtitle
>             // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
>         }
>     }
> 
>     struct CircleProgressNSSStyle: ProgressStyle {
>         let kpiProgressItemConfiguration: KPIProgressItemConfiguration
>         let nssData: NSSStyleData
> 
>         func makeBody(_ configuration: CircleProgressConfiguration) -> some View {
>             CircleProgress(configuration)
>                 .modifier(NSSStyleModifier<NSSBaseStyleType>(styles: self.nssData))
>             // Add custom nss style for Circleprogress
>             // .modifier(NSSStyleModifier<<#T: NSSCovert & RawRepresentable#>>(styles: <#T##NSSStyleData#>)
>         }
>     }
> }
> ```
> 
> Since my current pull request is still under review, for reference only.

Updated the code, app dev can customize the style for every part now.

2025-01-07 02:12 UTC, KevinZK approved these changes

2025-01-07 02:43 UTC, dyongxu approved these changes

2025-01-07 02:45 UTC, merged