refactor: 💡 [JIRA:HCPSDKFIORIUIKIT-2880] ActionItems Refactor
SAP/cloud-sdk-ios-fiori pull request #939
Opened 2024-12-16 02:05 UTC by hengyi-zhang

2024-12-17 10:06 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/_FioriStyles/ActionItemsStyle.fiori.swift
> +                        .frame(width: 44, height: 44, alignment: .center)
Here, I am not sure if the icon should support customization or not. For now, I think the color always 'blue' here and consumer don't have chance to change it. 
So, maybe, we can add a bool flag, isCustom = false, in ActivityItemDataType and don't set those font, foregroundColor something like that when isCustom = true. In additional, add new constructer, public init(type: ActivityItemType, data: String? = nil, isCustom: Bool), for API backward compatibility and let consumer have a chance to set a customized icon.
@xiaoyu0722 @dyongxu do you think we need support the customization?

2024-12-17 18:32 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/ActionItemsStyle.fiori.swift
> +                        .frame(width: 44, height: 44, alignment: .center)
I think all elements in our UI (including icon) should allow customization, i.e. App developer can override the font/color etc if their App Designer prefers another theming. So we should have a way to allow this.

2024-12-19 05:58 UTC, JunSong-SH approved these changes
LGTM!

2024-12-19 07:45 UTC, xiaoyu0722 requested changes

2024-12-19 07:45 UTC, xiaoyu0722 commented on Apps/Examples/Examples/FioriSwiftUICore/ActionItems/ActionItemsExample.swift
> +struct ActionItemsExample: View {
`ActionItems` not `ActivityItem`?
I'm not sure if we need an individual example for this sub-component. Or should put it into `ActivityItem` category.

2024-12-19 07:45 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/Views/ActionItems/ActionItemsBuilder.swift
> +struct ActionItemsListStack: ActionItemsList {
Seems same with `IndexedViewContainer`, you can use `struct ActionItemsListStack: IndexedViewContainer` directly.

2024-12-19 07:45 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_ComponentProtocols/BaseComponentProtocols.swift
> +    // sourcery: resultBuilder.name = @ActionItemsBuilder, resultBuilder.backingComponent = ActionItemsListStack
Try below annotation.
```swift
// sourcery: resultBuilder.name = @IndexedViewBuilder
// sourcery: resultBuilder.backingComponent = ActionItemsListStack
// sourcery: resultBuilder.returnType = any IndexedViewContainer
```

2024-12-19 08:33 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/Views/ActionItems/ActionItemsBuilder.swift
> +struct ActionItemsListStack: ActionItemsList {
IndexedViewContainer doesn't conform View protocol

2024-12-20 09:07 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/Views/ActionItems/ActionItemsBuilder.swift
> +                    .frame(width: 44, height: 44, alignment: .center)
fixed

2024-12-20 09:12 UTC, hengyi-zhang commented on Apps/Examples/Examples/FioriSwiftUICore/ActionItems/ActionItemsExample.swift
> +struct ActionItemsExample: View {
ActionItems not ActivityItem！

2024-12-23 05:58 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/ActionItemsStyle.fiori.swift
> +        configuration.actionItems
configuration.actionItems should be treated as one single View.

2024-12-23 05:58 UTC, xiaoyu0722 approved these changes

2024-12-23 06:03 UTC, hengyi-zhang commented on Sources/FioriSwiftUICore/_FioriStyles/ActionItemsStyle.fiori.swift
> +                        .frame(width: 44, height: 44, alignment: .center)
Developer can customize font and foregroundColor through .actionItemsStyle modifier, like in the example.

2024-12-25 02:08 UTC, merged