feat: 🎸 [HCPSDKFIORIUIKIT-2683] [SwiftUI] Slider
SAP/cloud-sdk-ios-fiori pull request #940
Opened 2024-12-17 07:38 UTC by JunSong-SH

This PR addresses changes to support the Slider in the SDK. 

[HCPSDKFIORIUIKIT-2683](https://jira.tools.sap/browse/HCPSDKFIORIUIKIT-2683) [SwiftUI] Slider
[HCPSDKFIORIUIKIT-2684](https://jira.tools.sap/browse/HCPSDKFIORIUIKIT-2684) [SwiftUI] Range Slider

The changes:

- Built new base components: _LowerThumbComponent, _UpperThumbComponent, _ActiveTrackComponent, _InactiveTrackComponent, _LeadingAccessoryComponent and _TrailingAccessoryComponent
- Built new composite components: _RangeSliderControlComponent, _FioriSliderComponent
- Implement the logic to let FioriSlider component support standard slider and range slider both
- Implement the Demo for FioriSlider. 

See below screenshot:

![StandardSlider](https://github.com/user-attachments/assets/8680c12d-9a11-4e10-9ce2-d8ff0bd64344)![RangeSlider](https://github.com/user-attachments/assets/e604e54e-b300-4200-91c6-e9ed95e5dc70)

2024-12-17 18:39 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +import FioriThemeManager
remove this line

2024-12-17 18:39 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +import SwiftUI
remove this line

2024-12-18 21:51 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    init(@ViewBuilder title: () -> any View,
The init at line 44 and line 126:
What is the major difference btw these two? Is it the extra property of "icon" ?
Can we merge these init into one ?
Same comments apply to other init of "range slider" ,  "single editable range slider", as well.

2024-12-18 21:57 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    /// The track represents a continuum between two extremes: a minimum and a maximum value.
```suggestion
    /// The track represents a continuum between two bounded values: a minimum and a maximum value.
```

2024-12-18 21:58 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    /// By default, the formatted minimum value is displayed at the leading end of the slider, and the formatted maximum value is displayed at the trailing end of the slider.
```suggestion
    /// By default, the formatted minimum value is displayed at the leading side of the slider, and the formatted maximum value is displayed at the trailing side of the slider.
```

2024-12-18 21:59 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    /// The title is displayed at the top left of the component, while the bound value is displayed at the top right. As users move the thumb, the slider continuously updates its bound value to refle
```suggestion
    /// The title is displayed at the top left of the component, while the bound value is displayed at the top right. As the user moves the thumb, the slider continuously updates its selected value corresponding to the thumb’s position.
```

2024-12-18 22:04 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - step: The distance between each valid value. The default is `1`.
```suggestion
    ///   - step: incremental/decremental value when the thumb changes its position. The default is `1`.
```

2024-12-19 01:05 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - leadingValueFormat: This optional format is used to format the displayed minimal value of standard slider's range in the leading accessory view. if provided.
```suggestion
    ///   - leadingValueFormat: This optional format is used to format the displayed minimal value of standard slider's range in the leading accessory view, if provided.
```

2024-12-19 01:10 UTC, dyongxu requested changes
Would like to see if possible to consolidate lots of the inits for different slides.

2024-12-19 01:10 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - trailingAccessory: The customized view to override the default trailing accessory view which was a text label to display the maximum value of the range
```suggestion
    ///   - trailingAccessory: The customized view to override the default trailing accessory view which is a text label to display the maximum value of the range
```

2024-12-19 01:10 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - trailingValueFormat: This optional format is used to format the displayed maximal value of standard slider's range in the trailing accessory view. if provided.
```suggestion
    ///   - trailingValueFormat: This optional format is used to format the displayed maximal value of standard slider's range in the trailing accessory view, if provided.
```

2024-12-19 01:10 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - thumb: the Shape for  thumb of the standard Slider. By default, it is Circle.
```suggestion
    ///   - thumb: the shape for thumb of the standard Slider. By default, it is circle.
```

2024-12-19 01:10 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - activeTrack: the Shape for active track of the standard Slider. By default, it is Capsule.
```suggestion
    ///   - activeTrack: the shape for active track of the standard Slider. By default, it is capsule.
```

2024-12-19 01:10 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    ///   - inactiveTrack: the Shape for inactive track of the standard Slider. By default, it is Capsule.
```suggestion
    ///   - inactiveTrack: the shape for inactive track of the standard Slider. By default, it is capsule.
```

2024-12-19 06:12 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    init(@ViewBuilder title: () -> any View,
The main difference is that the `AttributedString` type property, such as `title`, which is declared in `BaseComponent` with `@ViewBuilder`, will be used in two constructors: one with the `AttributedString` type and the other with `@ViewBuilder`, following our styled component approach. 

So, there are two constructors both for "standard slider", "range slider" and "single editable range slider". I think the reason is: By using the `AttributedString` type, the app team can implement less code, while with `@ViewBuilder`, the app team can customize it.

2024-12-19 21:54 UTC, dyongxu commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    init(@ViewBuilder title: () -> any View,
Would it make sense to merge them into sth like :
    init(title: AttributedString, @ViewBuilder titleView: () -> any View, .......)
 We can also define the priority, if both title and titleView are set by Application,  we will use title , and ignore titleView.

2024-12-20 07:05 UTC, JunSong-SH commented on Sources/FioriSwiftUICore/DataTypes/FioriSlider+DataType.swift
> +    init(@ViewBuilder title: () -> any View,
Fixed! Merge those constructor into one for "standard slider", "range slider" and "single editable range slider"

2024-12-20 09:56 UTC, JunSong-SH commented
Close this one and use new PR 945 for Slider

2024-12-20 09:56 UTC, closed without merging