refactor: 💡 step progress indicator
SAP/cloud-sdk-ios-fiori pull request #944
Opened 2024-12-19 01:48 UTC by xiaoyu0722

<img src="https://github.com/user-attachments/assets/0a753a91-781a-4275-b15c-dccf496fa535" width=50%>

2024-12-19 22:30 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// `StepProgressIndicator` is view support a list of `StepItem` in a  horizontal stack. Also customized steps is also supported.
```suggestion
/// `StepProgressIndicator` is a view supporting a list of `StepItem` in a  horizontal stack. Also customized steps are also supported.
```

2024-12-19 22:35 UTC, dyongxu commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// Only `stepStyle` will continue to be supported. And other legacy modifiers will be deprecated in the future. Please use latest modifiers.
Not sure why this needs to be noted here?
If this is actually needed, then, we need to specify what the legacy modifers are.
Otherwise, it will confuse the developer if the legacy modifiers refer to line 772 to line 776, since only stepStyle is mentioned in line 771

2024-12-19 22:37 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    /// Convenience initialization for default step progress indicator.
```suggestion
    /// Convenience initializer for default step progress indicator.
```

2024-12-19 22:42 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    ///   - title: Title for current step displayed on steps top-left .
```suggestion
    ///   - title: Title for current step displayed on the top leading side of the step progress indicator .
```
Usually we don't use the word left or right, since our control supports RTL layout

2024-12-19 22:48 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    ///   - action: Action for steps displayed on steps top-right that will show a vertical steps.
```suggestion
    ///   - action: Action for steps displayed on the top trailing side of the step progress indicator. It will show vertical steps.
```

2024-12-19 22:49 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    /// Convenience initialization for default step progress indicator.
```suggestion
    /// Convenience initializer for default step progress indicator.
```

2024-12-19 22:49 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    /// Convenience initialization for default step progress indicator.
```suggestion
    /// Convenience initializer for default step progress indicator.
```

2024-12-19 22:50 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    ///   - action: Action for steps displayed on steps top-right that will show a vertical steps.
```suggestion
    ///   - action: Action for steps displayed on steps top trailing side of the step progress indicator. It will show  vertical steps.
```

2024-12-19 22:50 UTC, dyongxu commented on Sources/FioriSwiftUICore/_FioriStyles/StepProgressIndicatorStyle.fiori.swift
> +    /// Convenience initialization for default step progress indicator.
```suggestion
    /// Convenience initializer for default step progress indicator.
```

2024-12-19 22:51 UTC, dyongxu requested changes
Doc update

2024-12-20 08:19 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_ComponentProtocols/CompositeComponentProtocols.swift
> +/// Only `stepStyle` will continue to be supported. And other legacy modifiers will be deprecated in the future. Please use latest modifiers.
Cause the template can not support indexed views styles update, so I added a note here to tell developers that `stepStyle()` can support to update style by id.
OK, I will update this doc.

2024-12-20 14:21 UTC, dyongxu approved these changes

2024-12-23 02:24 UTC, merged