refactor: 💡 [HCPSDKFIORIUIKIT-2879] KeyValueItem Refactor
SAP/cloud-sdk-ios-fiori pull request #949
Opened 2024-12-27 03:20 UTC by zuopengchi

2024-12-30 01:25 UTC, xiaoyu0722 commented on Sources/FioriCharts/Resources/sr-Latn-RS.lproj/Localizable.strings
> -
Please revert this.

2024-12-30 01:25 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_FioriStyles/KeyStyle.fiori.swift
> +// DO NOT EDIT
Remove these lines.

2024-12-30 01:25 UTC, xiaoyu0722 commented on Sources/FioriSwiftUICore/_FioriStyles/KeyValueItemStyle.fiori.swift
> +// DO NOT EDIT
Remove these lines.

2024-12-31 07:46 UTC, zuopengchi commented on Sources/FioriCharts/Resources/sr-Latn-RS.lproj/Localizable.strings
> -
revert

2025-01-30 23:20 UTC, dyongxu requested changes
resolve merge conflict

2025-02-12 06:35 UTC, closed without merging